apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-05-27T17:17:24Z"
  labels:
    app: rbac
    pod: rbac-worker-service
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:pod: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7bccdccd-27ed-46b4-93c1-a7b6db2386e2"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:appProtocol: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:pod: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: manager
    operation: Update
    time: "2021-05-27T17:17:24Z"
  name: rbac-worker-service
  namespace: hbi
  ownerReferences:
  - apiVersion: cloud.redhat.com/v1alpha1
    controller: true
    kind: ClowdApp
    name: rbac
    uid: 7bccdccd-27ed-46b4-93c1-a7b6db2386e2
  resourceVersion: "3643"
  uid: 0a28a8b3-c216-4b74-8243-0068ce0637de
spec:
  clusterIP: 10.96.3.118
  clusterIPs:
  - 10.96.3.118
  ports:
  - appProtocol: http
    name: metrics
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    pod: rbac-worker-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
