apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-05-27T17:17:24Z"
  labels:
    app: host-inventory
    pod: host-inventory-inventory-mq-p1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:pod: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e081a6a6-67ab-4558-a9cc-7e31c50dc67d"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:appProtocol: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:pod: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: manager
    operation: Update
    time: "2021-05-27T17:17:24Z"
  name: host-inventory-inventory-mq-p1
  namespace: hbi
  ownerReferences:
  - apiVersion: cloud.redhat.com/v1alpha1
    controller: true
    kind: ClowdApp
    name: host-inventory
    uid: e081a6a6-67ab-4558-a9cc-7e31c50dc67d
  resourceVersion: "3549"
  uid: 7f9a5754-9fb4-4f0c-b812-0a080f3f621a
spec:
  clusterIP: 10.100.229.145
  clusterIPs:
  - 10.100.229.145
  ports:
  - appProtocol: http
    name: metrics
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    pod: host-inventory-inventory-mq-p1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
