apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-05-27T17:17:25Z"
  generation: 1
  labels:
    app: rbac
    pod-template-hash: 69968d95b9
    service: db
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/desired-replicas: {}
          f:deployment.kubernetes.io/max-replicas: {}
          f:deployment.kubernetes.io/revision: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
          f:service: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7542cd25-eb38-4b72-a592-44dd1a035a7c"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:replicas: {}
        f:selector: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:pod-template-hash: {}
              f:service: {}
          f:spec:
            f:containers:
              k:{"name":"rbac-db"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"PGPASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_DATABASE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_MASTER_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_MASTER_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":5432,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/lib/pgsql/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"quay-cloudservices-pull"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"rbac-db"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
      f:status:
        f:availableReplicas: {}
        f:fullyLabeledReplicas: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-27T17:19:36Z"
  name: rbac-db-69968d95b9
  namespace: hbi
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: rbac-db
    uid: 7542cd25-eb38-4b72-a592-44dd1a035a7c
  resourceVersion: "4193"
  uid: aecbe4f0-25c6-4396-a9f7-e60c0e3b79f9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac
      pod-template-hash: 69968d95b9
      service: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rbac
        pod-template-hash: 69968d95b9
        service: db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: ZtcVNiQk0p7gRT1E
        - name: POSTGRESQL_PASSWORD
          value: 44ox9985pipQv2jg
        - name: PGPASSWORD
          value: UPQDFN1agGAIwdpW
        - name: POSTGRESQL_MASTER_USER
          value: postgres
        - name: POSTGRESQL_MASTER_PASSWORD
          value: UPQDFN1agGAIwdpW
        - name: POSTGRESQL_DATABASE
          value: rbac
        image: quay.io/cloudservices/postgresql-rds:12-1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: rbac-db
        ports:
        - containerPort: 5432
          name: database
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: rbac-db
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-cloudservices-pull
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: env-hbi-env
      serviceAccountName: env-hbi-env
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: rbac-db
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
