# flake8: noqa
"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from iqe_host_inventory_api_v7.models.active_tag import ActiveTag
from iqe_host_inventory_api_v7.models.active_tags import ActiveTags
from iqe_host_inventory_api_v7.models.canonical_facts_in import CanonicalFactsIn
from iqe_host_inventory_api_v7.models.canonical_facts_in_all_of_bios_uuid import (
    CanonicalFactsInAllOfBiosUuid,
)
from iqe_host_inventory_api_v7.models.canonical_facts_in_all_of_insights_id import (
    CanonicalFactsInAllOfInsightsId,
)
from iqe_host_inventory_api_v7.models.canonical_facts_in_all_of_satellite_id import (
    CanonicalFactsInAllOfSatelliteId,
)
from iqe_host_inventory_api_v7.models.canonical_facts_in_all_of_subscription_manager_id import (
    CanonicalFactsInAllOfSubscriptionManagerId,
)
from iqe_host_inventory_api_v7.models.canonical_facts_out import CanonicalFactsOut
from iqe_host_inventory_api_v7.models.create_check_in import CreateCheckIn
from iqe_host_inventory_api_v7.models.fact_set import FactSet
from iqe_host_inventory_api_v7.models.group_in import GroupIn
from iqe_host_inventory_api_v7.models.group_out import GroupOut
from iqe_host_inventory_api_v7.models.group_out_with_host_count import GroupOutWithHostCount
from iqe_host_inventory_api_v7.models.group_query_output import GroupQueryOutput
from iqe_host_inventory_api_v7.models.host_id_out import HostIdOut
from iqe_host_inventory_api_v7.models.host_out import HostOut
from iqe_host_inventory_api_v7.models.host_query_output import HostQueryOutput
from iqe_host_inventory_api_v7.models.host_system_profile_out import HostSystemProfileOut
from iqe_host_inventory_api_v7.models.pagination_out import PaginationOut
from iqe_host_inventory_api_v7.models.patch_host_in import PatchHostIn
from iqe_host_inventory_api_v7.models.per_reporter_staleness import PerReporterStaleness
from iqe_host_inventory_api_v7.models.resource_types_groups_query_output import (
    ResourceTypesGroupsQueryOutput,
)
from iqe_host_inventory_api_v7.models.resource_types_out import ResourceTypesOut
from iqe_host_inventory_api_v7.models.resource_types_pagination_out import (
    ResourceTypesPaginationOut,
)
from iqe_host_inventory_api_v7.models.resource_types_pagination_out_links import (
    ResourceTypesPaginationOutLinks,
)
from iqe_host_inventory_api_v7.models.resource_types_pagination_out_meta import (
    ResourceTypesPaginationOutMeta,
)
from iqe_host_inventory_api_v7.models.resource_types_query_output import ResourceTypesQueryOutput
from iqe_host_inventory_api_v7.models.staleness_id import StalenessId
from iqe_host_inventory_api_v7.models.staleness_in import StalenessIn
from iqe_host_inventory_api_v7.models.staleness_output import StalenessOutput
from iqe_host_inventory_api_v7.models.structured_tag import StructuredTag
from iqe_host_inventory_api_v7.models.system_default_id import SystemDefaultId
from iqe_host_inventory_api_v7.models.system_profile import SystemProfile
from iqe_host_inventory_api_v7.models.system_profile_ansible import SystemProfileAnsible
from iqe_host_inventory_api_v7.models.system_profile_bootc_status import SystemProfileBootcStatus
from iqe_host_inventory_api_v7.models.system_profile_bootc_status_booted import (
    SystemProfileBootcStatusBooted,
)
from iqe_host_inventory_api_v7.models.system_profile_by_host_out import SystemProfileByHostOut
from iqe_host_inventory_api_v7.models.system_profile_conversions import SystemProfileConversions
from iqe_host_inventory_api_v7.models.system_profile_disk_device import SystemProfileDiskDevice
from iqe_host_inventory_api_v7.models.system_profile_dnf_module import SystemProfileDnfModule
from iqe_host_inventory_api_v7.models.system_profile_image_builder import SystemProfileImageBuilder
from iqe_host_inventory_api_v7.models.system_profile_installed_product import (
    SystemProfileInstalledProduct,
)
from iqe_host_inventory_api_v7.models.system_profile_inter_systems_running_instance import (
    SystemProfileInterSystemsRunningInstance,
)
from iqe_host_inventory_api_v7.models.system_profile_intersystems import SystemProfileIntersystems
from iqe_host_inventory_api_v7.models.system_profile_mssql import SystemProfileMssql
from iqe_host_inventory_api_v7.models.system_profile_nested_object_value import (
    SystemProfileNestedObjectValue,
)
from iqe_host_inventory_api_v7.models.system_profile_network_interface import (
    SystemProfileNetworkInterface,
)
from iqe_host_inventory_api_v7.models.system_profile_operating_system import (
    SystemProfileOperatingSystem,
)
from iqe_host_inventory_api_v7.models.system_profile_operating_system_out import (
    SystemProfileOperatingSystemOut,
)
from iqe_host_inventory_api_v7.models.system_profile_operating_system_out_results_inner import (
    SystemProfileOperatingSystemOutResultsInner,
)
from iqe_host_inventory_api_v7.models.system_profile_operating_system_out_results_inner_value import (
    SystemProfileOperatingSystemOutResultsInnerValue,
)
from iqe_host_inventory_api_v7.models.system_profile_rhel_ai import SystemProfileRhelAi
from iqe_host_inventory_api_v7.models.system_profile_rhsm import SystemProfileRhsm
from iqe_host_inventory_api_v7.models.system_profile_rpm_ostree_deployments_inner import (
    SystemProfileRpmOstreeDeploymentsInner,
)
from iqe_host_inventory_api_v7.models.system_profile_sap import SystemProfileSap
from iqe_host_inventory_api_v7.models.system_profile_sap_system_out import (
    SystemProfileSapSystemOut,
)
from iqe_host_inventory_api_v7.models.system_profile_sap_system_out_results_inner import (
    SystemProfileSapSystemOutResultsInner,
)
from iqe_host_inventory_api_v7.models.system_profile_sap_system_out_results_inner_value import (
    SystemProfileSapSystemOutResultsInnerValue,
)
from iqe_host_inventory_api_v7.models.system_profile_system_purpose import (
    SystemProfileSystemPurpose,
)
from iqe_host_inventory_api_v7.models.system_profile_systemd import SystemProfileSystemd
from iqe_host_inventory_api_v7.models.system_profile_third_party_services import (
    SystemProfileThirdPartyServices,
)
from iqe_host_inventory_api_v7.models.system_profile_third_party_services_crowdstrike import (
    SystemProfileThirdPartyServicesCrowdstrike,
)
from iqe_host_inventory_api_v7.models.system_profile_workloads import SystemProfileWorkloads
from iqe_host_inventory_api_v7.models.system_profile_workloads_ibm_db2 import (
    SystemProfileWorkloadsIbmDb2,
)
from iqe_host_inventory_api_v7.models.system_profile_workloads_oracle_db import (
    SystemProfileWorkloadsOracleDb,
)
from iqe_host_inventory_api_v7.models.system_profile_workloads_rhel_ai import (
    SystemProfileWorkloadsRhelAi,
)
from iqe_host_inventory_api_v7.models.system_profile_workloads_rhel_ai_gpu_models_inner import (
    SystemProfileWorkloadsRhelAiGpuModelsInner,
)
from iqe_host_inventory_api_v7.models.system_profile_yum_repo import SystemProfileYumRepo
from iqe_host_inventory_api_v7.models.tag_count_out import TagCountOut
from iqe_host_inventory_api_v7.models.tags_out import TagsOut
