"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class AppSortableFields(str, Enum):
    """
    Application data fields available for sorting in the /hosts-view endpoint. Use format `app_name:field_name` with the `order_by` parameter.  **Advisor** - `advisor:recommendations` - Number of Advisor recommendations - `advisor:incidents` - Number of Advisor incidents  **Vulnerability** - `vulnerability:total_cves` - Total CVE count - `vulnerability:critical_cves` - Critical severity CVEs  **Patch** - `patch:advisories_rhsa_installable` - Number of RHSA installable advisories - `patch:packages_installable` - Number of installable packages  **Remediations** - `remediations:remediations_plans` - Active remediation plans count  **Compliance** - `compliance:last_scan` - Last compliance scan timestamp  **Malware** - `malware:last_matches` - Malware matches count - `malware:last_scan` - Last malware scan timestamp
    """

    """
    allowed enum values
    """
    ADVISOR_COLON_RECOMMENDATIONS = "advisor:recommendations"
    ADVISOR_COLON_INCIDENTS = "advisor:incidents"
    VULNERABILITY_COLON_TOTAL_CVES = "vulnerability:total_cves"
    VULNERABILITY_COLON_CRITICAL_CVES = "vulnerability:critical_cves"
    PATCH_COLON_ADVISORIES_RHSA_INSTALLABLE = "patch:advisories_rhsa_installable"
    PATCH_COLON_PACKAGES_INSTALLABLE = "patch:packages_installable"
    REMEDIATIONS_COLON_REMEDIATIONS_PLANS = "remediations:remediations_plans"
    COMPLIANCE_COLON_LAST_SCAN = "compliance:last_scan"
    MALWARE_COLON_LAST_MATCHES = "malware:last_matches"
    MALWARE_COLON_LAST_SCAN = "malware:last_scan"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppSortableFields from a JSON string"""
        return cls(json.loads(json_str))
