"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictStr


class CanonicalFactsOut(BaseModel):
    """
    CanonicalFactsOut
    """

    insights_id: StrictStr | None = Field(
        default=None,
        description="An ID defined in /etc/insights-client/machine-id. This field is considered a canonical fact.",
    )
    subscription_manager_id: StrictStr | None = Field(
        default=None,
        description="A Red Hat Subcription Manager ID of a RHEL host.  This field is considered to be a canonical fact.",
    )
    satellite_id: StrictStr | None = Field(
        default=None,
        description="A Red Hat Satellite ID of a RHEL host.  This field is considered to be a canonical fact.",
    )
    bios_uuid: StrictStr | None = Field(
        default=None,
        description="A UUID of the host machine BIOS.  This field is considered to be a canonical fact.",
    )
    ip_addresses: list[StrictStr] | None = Field(
        default=None,
        description="Host’s network IP addresses.  This field is considered to be a canonical fact.",
    )
    fqdn: StrictStr | None = Field(
        default=None,
        description="A host’s Fully Qualified Domain Name.  This field is considered to be a canonical fact.",
    )
    mac_addresses: list[StrictStr] | None = Field(
        default=None,
        description="Host’s network interfaces MAC addresses.  This field is considered to be a canonical fact.",
    )
    provider_id: StrictStr | None = Field(
        default=None,
        description="Host’s reference in the external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM etc. This field is one of the canonical facts and does not work without provider_type.",
    )
    provider_type: StrictStr | None = Field(
        default=None,
        description="Type of external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM, etc. This field is one of the canonical facts and does not workout provider_id.",
    )
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "insights_id",
        "subscription_manager_id",
        "satellite_id",
        "bios_uuid",
        "ip_addresses",
        "fqdn",
        "mac_addresses",
        "provider_id",
        "provider_type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CanonicalFactsOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if insights_id (nullable) is None
        # and model_fields_set contains the field
        if self.insights_id is None and "insights_id" in self.model_fields_set:
            _dict["insights_id"] = None

        # set to None if subscription_manager_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.subscription_manager_id is None
            and "subscription_manager_id" in self.model_fields_set
        ):
            _dict["subscription_manager_id"] = None

        # set to None if satellite_id (nullable) is None
        # and model_fields_set contains the field
        if self.satellite_id is None and "satellite_id" in self.model_fields_set:
            _dict["satellite_id"] = None

        # set to None if bios_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.bios_uuid is None and "bios_uuid" in self.model_fields_set:
            _dict["bios_uuid"] = None

        # set to None if ip_addresses (nullable) is None
        # and model_fields_set contains the field
        if self.ip_addresses is None and "ip_addresses" in self.model_fields_set:
            _dict["ip_addresses"] = None

        # set to None if fqdn (nullable) is None
        # and model_fields_set contains the field
        if self.fqdn is None and "fqdn" in self.model_fields_set:
            _dict["fqdn"] = None

        # set to None if mac_addresses (nullable) is None
        # and model_fields_set contains the field
        if self.mac_addresses is None and "mac_addresses" in self.model_fields_set:
            _dict["mac_addresses"] = None

        # set to None if provider_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_id is None and "provider_id" in self.model_fields_set:
            _dict["provider_id"] = None

        # set to None if provider_type (nullable) is None
        # and model_fields_set contains the field
        if self.provider_type is None and "provider_type" in self.model_fields_set:
            _dict["provider_type"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CanonicalFactsOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "insights_id": obj.get("insights_id"),
            "subscription_manager_id": obj.get("subscription_manager_id"),
            "satellite_id": obj.get("satellite_id"),
            "bios_uuid": obj.get("bios_uuid"),
            "ip_addresses": obj.get("ip_addresses"),
            "fqdn": obj.get("fqdn"),
            "mac_addresses": obj.get("mac_addresses"),
            "provider_id": obj.get("provider_id"),
            "provider_type": obj.get("provider_type"),
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
