"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict

from iqe_host_inventory_api_v7.models.advisor_app_data import AdvisorAppData
from iqe_host_inventory_api_v7.models.compliance_app_data import ComplianceAppData
from iqe_host_inventory_api_v7.models.malware_app_data import MalwareAppData
from iqe_host_inventory_api_v7.models.patch_app_data import PatchAppData
from iqe_host_inventory_api_v7.models.remediations_app_data import RemediationsAppData
from iqe_host_inventory_api_v7.models.vulnerability_app_data import VulnerabilityAppData


class ConsumerApplicationsData(BaseModel):
    """
    Application-specific metrics and metadata associated with a host.
    """

    advisor: AdvisorAppData | None = None
    vulnerability: VulnerabilityAppData | None = None
    patch: PatchAppData | None = None
    remediations: RemediationsAppData | None = None
    compliance: ComplianceAppData | None = None
    malware: MalwareAppData | None = None
    __properties: ClassVar[list[str]] = [
        "advisor",
        "vulnerability",
        "patch",
        "remediations",
        "compliance",
        "malware",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ConsumerApplicationsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of advisor
        if self.advisor:
            _dict["advisor"] = self.advisor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vulnerability
        if self.vulnerability:
            _dict["vulnerability"] = self.vulnerability.to_dict()
        # override the default output from pydantic by calling `to_dict()` of patch
        if self.patch:
            _dict["patch"] = self.patch.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remediations
        if self.remediations:
            _dict["remediations"] = self.remediations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of compliance
        if self.compliance:
            _dict["compliance"] = self.compliance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of malware
        if self.malware:
            _dict["malware"] = self.malware.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ConsumerApplicationsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in ConsumerApplicationsData) in the input: "
                    + _key
                )

        _obj = cls.model_validate({
            "advisor": AdvisorAppData.from_dict(obj["advisor"])
            if obj.get("advisor") is not None
            else None,
            "vulnerability": VulnerabilityAppData.from_dict(obj["vulnerability"])
            if obj.get("vulnerability") is not None
            else None,
            "patch": PatchAppData.from_dict(obj["patch"])
            if obj.get("patch") is not None
            else None,
            "remediations": RemediationsAppData.from_dict(obj["remediations"])
            if obj.get("remediations") is not None
            else None,
            "compliance": ComplianceAppData.from_dict(obj["compliance"])
            if obj.get("compliance") is not None
            else None,
            "malware": MalwareAppData.from_dict(obj["malware"])
            if obj.get("malware") is not None
            else None,
        })
        return _obj
