"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictStr


class PatchAppData(BaseModel):
    """
    PatchAppData
    """

    advisories_rhsa_applicable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_rhba_applicable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_rhea_applicable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_other_applicable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_rhsa_installable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_rhba_installable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_rhea_installable: Annotated[int, Field(strict=True, ge=0)] | None = None
    advisories_other_installable: Annotated[int, Field(strict=True, ge=0)] | None = None
    packages_applicable: Annotated[int, Field(strict=True, ge=0)] | None = None
    packages_installable: Annotated[int, Field(strict=True, ge=0)] | None = None
    packages_installed: Annotated[int, Field(strict=True, ge=0)] | None = None
    template_name: StrictStr | None = None
    template_uuid: StrictStr | None = None
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "advisories_rhsa_applicable",
        "advisories_rhba_applicable",
        "advisories_rhea_applicable",
        "advisories_other_applicable",
        "advisories_rhsa_installable",
        "advisories_rhba_installable",
        "advisories_rhea_installable",
        "advisories_other_installable",
        "packages_applicable",
        "packages_installable",
        "packages_installed",
        "template_name",
        "template_uuid",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PatchAppData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if advisories_rhsa_applicable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhsa_applicable is None
            and "advisories_rhsa_applicable" in self.model_fields_set
        ):
            _dict["advisories_rhsa_applicable"] = None

        # set to None if advisories_rhba_applicable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhba_applicable is None
            and "advisories_rhba_applicable" in self.model_fields_set
        ):
            _dict["advisories_rhba_applicable"] = None

        # set to None if advisories_rhea_applicable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhea_applicable is None
            and "advisories_rhea_applicable" in self.model_fields_set
        ):
            _dict["advisories_rhea_applicable"] = None

        # set to None if advisories_other_applicable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_other_applicable is None
            and "advisories_other_applicable" in self.model_fields_set
        ):
            _dict["advisories_other_applicable"] = None

        # set to None if advisories_rhsa_installable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhsa_installable is None
            and "advisories_rhsa_installable" in self.model_fields_set
        ):
            _dict["advisories_rhsa_installable"] = None

        # set to None if advisories_rhba_installable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhba_installable is None
            and "advisories_rhba_installable" in self.model_fields_set
        ):
            _dict["advisories_rhba_installable"] = None

        # set to None if advisories_rhea_installable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_rhea_installable is None
            and "advisories_rhea_installable" in self.model_fields_set
        ):
            _dict["advisories_rhea_installable"] = None

        # set to None if advisories_other_installable (nullable) is None
        # and model_fields_set contains the field
        if (
            self.advisories_other_installable is None
            and "advisories_other_installable" in self.model_fields_set
        ):
            _dict["advisories_other_installable"] = None

        # set to None if packages_applicable (nullable) is None
        # and model_fields_set contains the field
        if self.packages_applicable is None and "packages_applicable" in self.model_fields_set:
            _dict["packages_applicable"] = None

        # set to None if packages_installable (nullable) is None
        # and model_fields_set contains the field
        if self.packages_installable is None and "packages_installable" in self.model_fields_set:
            _dict["packages_installable"] = None

        # set to None if packages_installed (nullable) is None
        # and model_fields_set contains the field
        if self.packages_installed is None and "packages_installed" in self.model_fields_set:
            _dict["packages_installed"] = None

        # set to None if template_name (nullable) is None
        # and model_fields_set contains the field
        if self.template_name is None and "template_name" in self.model_fields_set:
            _dict["template_name"] = None

        # set to None if template_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.template_uuid is None and "template_uuid" in self.model_fields_set:
            _dict["template_uuid"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PatchAppData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "advisories_rhsa_applicable": obj.get("advisories_rhsa_applicable"),
            "advisories_rhba_applicable": obj.get("advisories_rhba_applicable"),
            "advisories_rhea_applicable": obj.get("advisories_rhea_applicable"),
            "advisories_other_applicable": obj.get("advisories_other_applicable"),
            "advisories_rhsa_installable": obj.get("advisories_rhsa_installable"),
            "advisories_rhba_installable": obj.get("advisories_rhba_installable"),
            "advisories_rhea_installable": obj.get("advisories_rhea_installable"),
            "advisories_other_installable": obj.get("advisories_other_installable"),
            "packages_applicable": obj.get("packages_applicable"),
            "packages_installable": obj.get("packages_installable"),
            "packages_installed": obj.get("packages_installed"),
            "template_name": obj.get("template_name"),
            "template_uuid": obj.get("template_uuid"),
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
