"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field

from iqe_host_inventory_api_v7.models.system_profile_workloads_rhel_ai_gpu_models_inner import (
    SystemProfileWorkloadsRhelAiGpuModelsInner,
)


class SystemProfileWorkloadsRhelAi(BaseModel):
    """
    Object containing information about RHEL AI
    """

    variant: Annotated[str, Field(strict=True, max_length=7)] | None = Field(
        default=None, description="RHEL AI VARIANT"
    )
    rhel_ai_version_id: Annotated[str, Field(strict=True, max_length=16)] | None = Field(
        default=None, description="RHEL AI VERSION ID"
    )
    gpu_models: list[SystemProfileWorkloadsRhelAiGpuModelsInner] | None = Field(
        default=None, description="The list of GPU models on the host"
    )
    ai_models: list[Annotated[str, Field(strict=True, max_length=256)]] | None = Field(
        default=None, description="The list of AI models available on the host"
    )
    free_disk_storage: Annotated[str, Field(strict=True, max_length=32)] | None = Field(
        default=None, description="The free storage available on the host"
    )
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "variant",
        "rhel_ai_version_id",
        "gpu_models",
        "ai_models",
        "free_disk_storage",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SystemProfileWorkloadsRhelAi from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gpu_models (list)
        _items = []
        if self.gpu_models:
            for _item in self.gpu_models:
                if _item:
                    _items.append(_item.to_dict())
            _dict["gpu_models"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SystemProfileWorkloadsRhelAi from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "variant": obj.get("variant"),
            "rhel_ai_version_id": obj.get("rhel_ai_version_id"),
            "gpu_models": [
                SystemProfileWorkloadsRhelAiGpuModelsInner.from_dict(_item)
                for _item in obj["gpu_models"]
            ]
            if obj.get("gpu_models") is not None
            else None,
            "ai_models": obj.get("ai_models"),
            "free_disk_storage": obj.get("free_disk_storage"),
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
