"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictInt

from iqe_host_inventory_api_v7.models.structured_tag import StructuredTag


class TagsOut(BaseModel):
    """
    TagsOut
    """

    count: StrictInt = Field(description="The number of items on the current page")
    page: StrictInt = Field(description="The page number")
    per_page: StrictInt = Field(description="The number of items to return per page")
    total: StrictInt = Field(description="Total number of items")
    results: dict[str, list[StructuredTag]] | None = Field(
        default=None, description="The list of tags on the systems"
    )
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = ["count", "page", "per_page", "total", "results"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TagsOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in results (dict of array)
        _field_dict_of_array = {}
        if self.results:
            for _key in self.results:
                if self.results[_key] is not None:
                    _field_dict_of_array[_key] = [_item.to_dict() for _item in self.results[_key]]
            _dict["results"] = _field_dict_of_array
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TagsOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "page": obj.get("page"),
            "per_page": obj.get("per_page"),
            "total": obj.get("total"),
            "results": {
                _k: [StructuredTag.from_dict(_item) for _item in _v] if _v is not None else None
                for _k, _v in obj.get("results", {}).items()
            },
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
