version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: insights
            POSTGRES_USER: insights
            POSTGRES_DB: test_db
        ports: 
            - "5432:5432"
