version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: insights
            POSTGRES_USER: insights
            POSTGRES_DB: insights
        ports:
            - "5432:5432"
        volumes:
          - ./.unleash/create_unleashdb.sql:/docker-entrypoint-initdb.d/create_unleashdb.sql
    zookeeper:
      image: confluentinc/cp-zookeeper
      environment:
        - ZOOKEEPER_CLIENT_PORT=32181
        - ZOOKEEPER_SERVER_ID=1
    kafka:
      image: confluentinc/cp-kafka
      ports:
        - 29092:29092
      depends_on:
        - zookeeper
      environment:
        - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://kafka:29092
        - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        - KAFKA_BROKER_ID=1
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
    unleash:
      container_name: unleash
      image: quay.io/cloudservices/unleash-server:4.21.0
      environment:
        - INIT_ADMIN_API_TOKENS=${UNLEASH_TOKEN:?}
        - CHECK_VERSION=false
        - DATABASE_HOST=db
        - DATABASE_NAME=unleash
        - DATABASE_USERNAME=${DATABASE_USER-insights}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-insights}
        - DATABASE_SSL=false
        - IMPORT_DROP_BEFORE_IMPORT=false
        - IMPORT_FILE=/.unleash/flags.json
        - LOG_LEVEL=INFO
      ports:
        - 4242:4242
      volumes:
        - './.unleash:/.unleash'
      depends_on:
        - db
