version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: insights
            POSTGRES_USER: insights
            POSTGRES_DB: test_db
        ports: 
            - "5432:5432"
    web:
        build: .
        restart: always
        command: bash -c "sleep 2 && python manage.py db upgrade && python manage.py db migrate && ./run.py"
        environment:
            INVENTORY_DB_HOST: db
        ports:
            - "5000:5000"
        depends_on:
            - db
