apiVersion: v1
kind: Pod
metadata:
  name: unit-test-db
  labels:
    test: db
spec:
  containers:
  - name: postgres
    image: quay.io/app-sre/postgres:9.6
    env:
    - name: POSTGRES_USER
      value: insights
    - name: POSTGRES_PASSWORD
      value: insights
    - name: POSTGRES_DB
      value: insights
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    volumeMounts:
    - mountPath: /var/lib/postgresql/data/pgdata
      name: data
    ports:
    - containerPort: 5432
      name: db
      protocol: TCP
  volumes:
  - emptyDir: {}
    name: data
