[pytest]
addopts = --ignore swagger --ignore iqe-host-inventory-plugin --ignore librdkafka
    --ignore tests/test_jobs/test_backfill_per_reporter_culled_timestamps.py
    --ignore tests/test_jobs/test_duplicate_hosts.py
markers =
  system_profile
  system_culling
  host_synchronizer
  host_delete_duplicates
  host_reaper
