swagger: "2.0"
info:
  description: Swagger doc that describes the Host Inventory REST interface
  version: 1.0.0
  title: Host Inventory ReST Interface
consumes:
- application/json
produces:
- application/json
basePath: /api

parameters:
  rhIdentityHeader:
    in: header
    name: x-rh-identity
    required: true
    type: string
    format: byte
  pageParam:
    in: query
    name: page
    required: false
    type: integer
    minimum: 1
    default: 1
    description: The page number of the items to return.
  perPageParam:
    in: query
    name: per_page
    required: false
    type: integer
    minimum: 1
    maximum: 100
    default: 50
    description: The numbers of items to return per page.

paths:
  /hosts:
    parameters:
      - $ref: '#/parameters/rhIdentityHeader'
    get:
      operationId: api.host.getHostList
      tags:
      - hosts
      summary: Read the entire list of hosts
      description: Read the list of hosts
      parameters:
        - name: tag
          in: query
          type: array
          items:
            type: string
          description: Search by tags
          required: false
          collectionFormat: multi
        - name: display_name
          in: query
          type: string
          description: Search by display_name
          required: false
        - $ref: '#/parameters/perPageParam'
        - $ref: '#/parameters/pageParam'
      responses:
        "200":
          description: Successfully read hosts list operation
          schema:
            $ref: '#/definitions/HostQueryOutput'
    post:
      operationId: api.host.addHost
      tags:
      - hosts
      summary: Create a host and add it to the hosts list
      description: Create a new host in the hosts list
      parameters:
      - in: body
        name: host
        description: Host object that needs to be added to the store
        required: true
        schema:
          $ref: '#/definitions/Host'
      responses:
        "201":
          description: Successfully created host in list
        "200":
          description: Successfully updated a host in list
  '/hosts/{hostId}':
    parameters:
      - $ref: '#/parameters/rhIdentityHeader'
    get:
      tags:
      - hosts
      summary: Find host by ID
      description: Returns a single host or list of hosts
      operationId: api.host.getHostById
      produces:
      - application/json
      parameters:
        - name: hostId
          in: path
          description: ID of host to return
          required: true
          type: array
          collectionFormat: csv
          items:
            type: string
        - $ref: '#/parameters/perPageParam'
        - $ref: '#/parameters/pageParam'
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/HostQueryOutput'
        '400':
          description: Invalid ID supplied
        "404":
          description: Host not found
   # delete:
   #   tags:
   #     - hosts
   #   summary: Deletes a host
   #   description: ''
   #   operationId: api.host.deleteHost
   #   produces:
   #     - application/json
   #   parameters:
   #     - name: hostId
   #       in: path
   #       description: Host id to delete
   #       required: true
   #       type: integer
   #       format: int64
   #   responses:
   #     '400':
   #       description: Invalid ID supplied
   #     '404':
   #       description: Host not found
  '/hosts/{hostId}/facts/{namespace}':
    parameters:
      - $ref: '#/parameters/rhIdentityHeader'
    patch:
      tags:
      - hosts
      summary: Merge facts under a namespace
      description: Merge facts
      operationId: api.host.mergeFacts
      produces:
      - application/json
      parameters:
      - name: hostId
        in: path
        description: ID of host to return
        required: true
        type: array
        collectionFormat: csv
        items:
          type: string
      - name: namespace
        in: path
        description: Namespace of the fact
        required: true
        type: string
      - in: body
        name: fact_dict
        description: Fact dictionary
        required: true
        schema:
          $ref: '#/definitions/Facts'
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Host not found
    put:
      tags:
      - hosts
      summary: Replace facts under a namespace
      description: Replace facts
      operationId: api.host.replaceFacts
      produces:
      - application/json
      parameters:
      - name: hostId
        in: path
        description: ID of host to return
        required: true
        type: array
        collectionFormat: csv
        items:
          type: string
      - name: namespace
        in: path
        description: Namespace of the fact
        required: true
        type: string
      - in: body
        name: fact_dict
        description: Fact dictionary
        required: true
        schema:
          $ref: '#/definitions/Facts'
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Host not found
  '/hosts/{hostId}/tags':
    parameters:
      - $ref: '#/parameters/rhIdentityHeader'
    post:
      operationId: api.host.handleTagOperation
      tags:
      - hosts
      summary: Add or remove a tag from a number of hosts
      description: Add or remove a tag from a number of hosts
      parameters:
      - name: hostId
        in: path
        description: ID of host to return
        required: true
        type: array
        collectionFormat: csv
        items:
          type: string
      - in: body
        name: tag_op
        description: Tag operation
        required: true
        schema:
          $ref: '#/definitions/TagOperation'
      responses:
        "200":
          description: Successfully added or removed a tag
definitions:
  Facts:
    type: object
    additionalProperties:
      type: string
    example:
      fact1: value1
      fact2: value2
  FactSet:
    properties:
      namespace:
        type: string
      facts:
        type: object
  Host:
    type: object
    required:
    - account
    properties:
      display_name:
        type: string
        example: host1.mydomain.com
      account:
        type: string
        example: "000102"
      insights_id:
        type: string
        format: uuid
        example: 3f01b55457674041b75e41829bcee1dc
        x-nullable: true
      rhel_machine_id:
        type: string
        format: uuid
        example: 3f01b55457674041b75e41829bcee1dc
        x-nullable: true
      subscription_manager_id:
        type: string
        format: uuid
        example: 3f01b55457674041b75e41829bcee1dc
        x-nullable: true
      satellite_id:
        type: string
        format: uuid
        example: 3f01b55457674041b75e41829bcee1dc
        x-nullable: true
      bios_uuid:
        type: string
        format: uuid
        example: 3f01b55457674041b75e41829bcee1dc
        x-nullable: true
      ip_addresses:
        type: array
        items:
          type: string
        x-nullable: true
        example:
        - 10.10.0.1
        - 10.0.0.2
      fqdn:
        type: string
        example: my.host.example.com
        x-nullable: true
      mac_addresses:
        type: array
        items:
          type: string
        x-nullable: true
        example:
        - c2:00:d0:c8:61:01
      facts:
        type: array
        items:
          $ref: '#/definitions/FactSet'
      tags:
        type: array
        items:
          type: string
  HostOut:
    allOf:
      - $ref: '#/definitions/Host'
      - type: object
        properties:
          id:
            type: string
            format: uuid
          created:
            type: string
            format: date-time
          updated:
            type: string
            format: date-time
  HostQueryOutput:
    type: object
    required:
      - count
      - page
      - per_page
      - total
      - results
    properties:
      count:
        type: integer
      page:
        type: integer
      per_page:
        type: integer
      total:
        type: integer
      results:
        type: array
        items:
          $ref: '#/definitions/HostOut'
  TagOperation:
    type: object
    required:
    - operation
    - tag
    properties:
      operation:
        type: string
        enum:
        - apply
        - remove
      tag:
        type: string
