---
openapi: 3.0.0
info:
  description: includes for pagination
  version: 1.0.0
  title: example pagination
paths: {}
components:
  parameters:
    pageParam:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description: A page number of the items to return.
    perPageParam:
      name: per_page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50
      description: A number of items to return per page.
  schemas:
    PaginationOut:
      type: object
      required:
        - count
        - page
        - per_page
        - total
      properties:
        count:
          $ref: '#/components/schemas/Count'
        page:
          $ref: '#/components/schemas/Page'
        per_page:
          $ref: '#/components/schemas/PerPage'
        total:
          $ref: '#/components/schemas/Total'
    Total:
      type: integer
      description: Total number of items
    Count:
      type: integer
      description: The number of items on the current page
    Page:
      type: integer
      description: The page number
    PerPage:
      type: integer
      description: The number of items to return per page
