apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-05-27T17:17:24Z"
  generation: 1
  labels:
    app: rbac
    pod: rbac-scheduler-service
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:pod: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7bccdccd-27ed-46b4-93c1-a7b6db2386e2"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:configHash: {}
            f:labels:
              .: {}
              f:app: {}
              f:pod: {}
          f:spec:
            f:affinity:
              .: {}
              f:podAntiAffinity:
                .: {}
                f:preferredDuringSchedulingIgnoredDuringExecution: {}
            f:containers:
              k:{"name":"rbac-scheduler-service"}:
                .: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"ACG_CONFIG"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"APP_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"CLOWDER_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CW_NULL_WORKAROUND"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DJANGO_DEBUG"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DJANGO_LOG_LEVEL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"GROUP_SEEDING_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PERMISSION_SEEDING_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ROLE_SEEDING_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SENTRY_DSN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                        f:optional: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/cdapp/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"quay-cloudservices-pull"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config-secret"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
    manager: manager
    operation: Update
    time: "2021-05-27T17:17:24Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-27T17:17:25Z"
  name: rbac-scheduler-service
  namespace: hbi
  ownerReferences:
  - apiVersion: cloud.redhat.com/v1alpha1
    controller: true
    kind: ClowdApp
    name: rbac
    uid: 7bccdccd-27ed-46b4-93c1-a7b6db2386e2
  resourceVersion: "3682"
  uid: 2fcf02a2-9df7-4549-8c04-8949b1857c35
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rbac
      pod: rbac-scheduler-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configHash: e604984da19467107497dfbb3c202238ebadc86134077bd330768f6831f4b18b
      creationTimestamp: null
      labels:
        app: rbac
        pod: rbac-scheduler-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: rbac
                  pod: rbac-scheduler-service
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: rbac
                  pod: rbac-scheduler-service
              topologyKey: kubernetes.io/hostname
            weight: 99
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          PYTHONPATH=${PWD}/rbac/ celery -A rbac.celery beat -l $DJANGO_LOG_LEVEL
        env:
        - name: DJANGO_LOG_LEVEL
          value: INFO
        - name: DJANGO_DEBUG
          value: "False"
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PERMISSION_SEEDING_ENABLED
          value: "False"
        - name: ROLE_SEEDING_ENABLED
          value: "False"
        - name: GROUP_SEEDING_ENABLED
          value: "False"
        - name: CLOWDER_ENABLED
          value: "true"
        - name: CW_NULL_WORKAROUND
          value: ${CW_NULL_WORKAROUND)
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: rbac-secret
              optional: true
        - name: ACG_CONFIG
          value: /cdapp/cdappconfig.json
        image: quay.io/cloudservices/rbac:20cad27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              PYTHONPATH=${PWD}/rbac/ celery inspect ping -A rbac.celery
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: rbac-scheduler-service
        ports:
        - containerPort: 9000
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              PYTHONPATH=${PWD}/rbac/ celery inspect ping -A rbac.celery
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 8Gi
          requests:
            cpu: 300m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cdapp/
          name: config-secret
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-cloudservices-pull
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rbac-app
      serviceAccountName: rbac-app
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-secret
        secret:
          defaultMode: 420
          secretName: rbac
status:
  conditions:
  - lastTransitionTime: "2021-05-27T17:17:25Z"
    lastUpdateTime: "2021-05-27T17:17:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-27T17:17:24Z"
    lastUpdateTime: "2021-05-27T17:17:25Z"
    message: ReplicaSet "rbac-scheduler-service-5cdfbfdc69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
