apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-05-27T17:17:24Z"
  generation: 1
  labels:
    app: rbac
    service: db
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:service: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7bccdccd-27ed-46b4-93c1-a7b6db2386e2"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:service: {}
          f:spec:
            f:containers:
              k:{"name":"rbac-db"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"PGPASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_DATABASE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_MASTER_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_MASTER_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POSTGRESQL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":5432,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/lib/pgsql/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"quay-cloudservices-pull"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"rbac-db"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
    manager: manager
    operation: Update
    time: "2021-05-27T17:17:24Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-27T17:19:36Z"
  name: rbac-db
  namespace: hbi
  ownerReferences:
  - apiVersion: cloud.redhat.com/v1alpha1
    controller: true
    kind: ClowdApp
    name: rbac
    uid: 7bccdccd-27ed-46b4-93c1-a7b6db2386e2
  resourceVersion: "4194"
  uid: 7542cd25-eb38-4b72-a592-44dd1a035a7c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rbac
      service: db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rbac
        service: db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: ZtcVNiQk0p7gRT1E
        - name: POSTGRESQL_PASSWORD
          value: 44ox9985pipQv2jg
        - name: PGPASSWORD
          value: UPQDFN1agGAIwdpW
        - name: POSTGRESQL_MASTER_USER
          value: postgres
        - name: POSTGRESQL_MASTER_PASSWORD
          value: UPQDFN1agGAIwdpW
        - name: POSTGRESQL_DATABASE
          value: rbac
        image: quay.io/cloudservices/postgresql-rds:12-1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: rbac-db
        ports:
        - containerPort: 5432
          name: database
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - $(POSTGRESQL_USER)
            - -d
            - $(POSTGRESQL_DATABASE)
            - -c
            - SELECT 1
          failureThreshold: 3
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: rbac-db
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-cloudservices-pull
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: env-hbi-env
      serviceAccountName: env-hbi-env
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: rbac-db
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-05-27T17:19:36Z"
    lastUpdateTime: "2021-05-27T17:19:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-27T17:17:25Z"
    lastUpdateTime: "2021-05-27T17:19:36Z"
    message: ReplicaSet "rbac-db-69968d95b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
