apiVersion: v1
kind: Template
metadata:
  name: insights-host-inventory-cjis-replica
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory
    name: hosts-table-migration-data-copy-${HOSTS_TABLE_MIGRATION_DATA_COPY_RUN_NUMBER}
  spec:
    appName: host-inventory
    jobs:
      - hosts-table-migration-data-copy
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory
    name: hosts-table-migration-switch-${HOSTS_TABLE_MIGRATION_SWITCH_RUN_NUMBER}
  spec:
    appName: host-inventory
    jobs:
      - hosts-table-migration-switch

parameters:
- name: HOSTS_TABLE_MIGRATION_DATA_COPY_RUN_NUMBER
  value: '1'
- name: HOSTS_TABLE_MIGRATION_SWITCH_RUN_NUMBER
  value: '1'
