apiVersion: v1
kind: Template
metadata:
  name: insights-host-inventory-cjis-replica
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory-replica
    name: duplicate-hosts-remover-${DUPLICATE_HOSTS_REMOVER_RUN_NUMBER}
  spec:
    appName: host-inventory-replica
    jobs:
      - duplicate-hosts-remover
parameters:
- name: DUPLICATE_HOSTS_REMOVER_RUN_NUMBER
  value: '1'
