apiVersion: v1
kind: Template
metadata:
  name: insights-host-inventory-cjis
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory
    name: sp-tables-migration-data-copy-${SP_TABLES_MIGRATION_DATA_COPY_RUN_NUMBER}
  spec:
    appName: host-inventory
    jobs:
      - sp-tables-migration-data-copy
parameters:
- name: SP_TABLES_MIGRATION_DATA_COPY_RUN_NUMBER
  value: '1'
