apiVersion: v1
kind: Template
metadata:
  name: insights-host-inventory-cjis-replica
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory-replica
    name: host-synchronizer-only-${SYNCHRONIZER_ONLY_RUN_NUMBER}
  spec:
    appName: host-inventory-replica
    jobs:
      - synchronizer-only
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory-replica
    name: create-ungrouped-groups-${CREATE_UNGROUPED_GROUPS_RUN_NUMBER}
  spec:
    appName: host-inventory-replica
    jobs:
      - create-ungrouped-host-groups
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: host-inventory-replica
    name: assign-ungrouped-hosts-${ASSIGN_UNGROUPED_HOSTS_RUN_NUMBER}
  spec:
    appName: host-inventory-replica
    jobs:
      - assign-ungrouped-host-groups

parameters:
- name: SYNCHRONIZER_ONLY_RUN_NUMBER
  value: '1'
- name: CREATE_UNGROUPED_GROUPS_RUN_NUMBER
  value: '1'
- name: ASSIGN_UNGROUPED_HOSTS_RUN_NUMBER
  value: '1'
