# Generated by Django 2.0.4 on 2018-05-16 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=10)),
                ("display_name", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("facts", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("tags", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("ids", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["account_number"], name="inventory_e_account_2e1d53_idx"
            ),
        ),
    ]
