# Generated by Django 2.0.4 on 2018-04-12 18:57

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_number", models.CharField(max_length=10)),
                ("facts", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("display_name", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("tags", django.contrib.postgres.fields.hstore.HStoreField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=200)),
                (
                    "from_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_entity",
                        to="inventory.Entity",
                    ),
                ),
                (
                    "to_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_entity",
                        to="inventory.Entity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entity",
            name="relationships",
            field=models.ManyToManyField(
                through="inventory.EntityRelationship", to="inventory.Entity"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["account_number"], name="inventory_e_account_2e1d53_idx"
            ),
        ),
    ]
