# Generated by Django 2.0.4 on 2018-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(model_name="entity", name="tags"),
        migrations.AddField(
            model_name="entity",
            name="tags",
            field=models.ManyToManyField(to="inventory.Tag"),
        ),
    ]
