# Generated by Django 2.0.4 on 2018-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180522_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='inventory_e_account_2e1d53_idx',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='account_number',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='inventory.Tag'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['account'], name='inventory_e_account_7f4862_idx'),
        ),
    ]
