# Generated by Django 2.0.4 on 2018-05-14 20:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_auto_20180514_1736")]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="ids",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
