# Generated by Django 2.0.4 on 2018-05-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180514_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='facts',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='ids',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Entity'),
        ),
        migrations.AddField(
            model_name='fact',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Entity'),
        ),
        migrations.AddField(
            model_name='alternativeid',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Entity'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='inventory_t_name_144e39_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['namespace'], name='inventory_f_namespa_7bc81f_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['name'], name='inventory_f_name_b9a7da_idx'),
        ),
        migrations.AddIndex(
            model_name='alternativeid',
            index=models.Index(fields=['namespace'], name='inventory_a_namespa_aed0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='alternativeid',
            index=models.Index(fields=['value'], name='inventory_a_value_6016a4_idx'),
        ),
    ]
