"""update host_apps_data_compliance

Revision ID: 155a5b49da2e
Revises: ccbe2d893d2d
Create Date: 2026-01-29 17:35:47.991059

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.models.constants import INVENTORY_SCHEMA

# revision identifiers, used by Alembic.
revision = "155a5b49da2e"
down_revision = "ccbe2d893d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosts_app_data_compliance", schema=INVENTORY_SCHEMA) as batch_op:
        batch_op.drop_column("policies")
        batch_op.add_column(
            sa.Column(
                "policies",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosts_app_data_compliance", schema=INVENTORY_SCHEMA) as batch_op:
        batch_op.drop_column("policies")
        batch_op.add_column(
            sa.Column(
                "policies",
                sa.INTEGER(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###
