"""update host_apps_data_compliance

Revision ID: 155a5b49da2e
Revises: d1f9cf7adbd5
Create Date: 2026-01-29 17:35:47.991059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.constants import INVENTORY_SCHEMA

# revision identifiers, used by Alembic.
revision = "155a5b49da2e"
down_revision = "d1f9cf7adbd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosts_app_data_compliance", schema=INVENTORY_SCHEMA) as batch_op:
        batch_op.alter_column("policies",
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosts_app_data_compliance", schema=INVENTORY_SCHEMA) as batch_op:
        batch_op.alter_column("policies",
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
