"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Annotated
from typing import Any

from pydantic import Field
from pydantic import StrictFloat
from pydantic import StrictInt
from pydantic import StrictStr
from pydantic import validate_call

from iqe_host_inventory_api_v7.api_client import ApiClient
from iqe_host_inventory_api_v7.api_client import RequestSerialized
from iqe_host_inventory_api_v7.api_response import ApiResponse
from iqe_host_inventory_api_v7.models.system_profile_nested_object_value import (
    SystemProfileNestedObjectValue,
)
from iqe_host_inventory_api_v7.models.system_profile_operating_system_out import (
    SystemProfileOperatingSystemOut,
)
from iqe_host_inventory_api_v7.models.system_profile_sap_system_out import (
    SystemProfileSapSystemOut,
)
from iqe_host_inventory_api_v7.rest import RESTResponseType


class SystemProfileApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def api_system_profile_get_operating_system(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SystemProfileOperatingSystemOut:
        """get all operating system versions and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_operating_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileOperatingSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_system_profile_get_operating_system_with_http_info(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SystemProfileOperatingSystemOut]:
        """get all operating system versions and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_operating_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileOperatingSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_system_profile_get_operating_system_without_preload_content(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get all operating system versions and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_operating_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileOperatingSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _api_system_profile_get_operating_system_serialize(
        self,
        tags,
        per_page,
        page,
        staleness,
        registered_with,
        filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
            "tags": "multi",
            "staleness": "multi",
            "registered_with": "multi",
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[str, str | bytes] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if tags is not None:
            _query_params.append(("tags", tags))

        if per_page is not None:
            _query_params.append(("per_page", per_page))

        if page is not None:
            _query_params.append(("page", page))

        if staleness is not None:
            _query_params.append(("staleness", staleness))

        if registered_with is not None:
            _query_params.append(("registered_with", registered_with))

        if filter is not None:
            _query_params.append(("filter", filter))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # authentication setting
        _auth_settings: list[str] = ["ApiKeyAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/system_profile/operating_system",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_system_profile_get_sap_sids(
        self,
        search: Annotated[
            StrictStr | None,
            Field(
                description="Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching."
            ),
        ] = None,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SystemProfileSapSystemOut:
        """get all sap sids values and counts on the account

        Required permissions: inventory:hosts:read

        :param search: Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching.
        :type search: str
        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_sids_serialize(
            search=search,
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_system_profile_get_sap_sids_with_http_info(
        self,
        search: Annotated[
            StrictStr | None,
            Field(
                description="Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching."
            ),
        ] = None,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SystemProfileSapSystemOut]:
        """get all sap sids values and counts on the account

        Required permissions: inventory:hosts:read

        :param search: Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching.
        :type search: str
        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_sids_serialize(
            search=search,
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_system_profile_get_sap_sids_without_preload_content(
        self,
        search: Annotated[
            StrictStr | None,
            Field(
                description="Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching."
            ),
        ] = None,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get all sap sids values and counts on the account

        Required permissions: inventory:hosts:read

        :param search: Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching.
        :type search: str
        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_sids_serialize(
            search=search,
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _api_system_profile_get_sap_sids_serialize(
        self,
        search,
        tags,
        per_page,
        page,
        staleness,
        registered_with,
        filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
            "tags": "multi",
            "staleness": "multi",
            "registered_with": "multi",
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[str, str | bytes] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if search is not None:
            _query_params.append(("search", search))

        if tags is not None:
            _query_params.append(("tags", tags))

        if per_page is not None:
            _query_params.append(("per_page", per_page))

        if page is not None:
            _query_params.append(("page", page))

        if staleness is not None:
            _query_params.append(("staleness", staleness))

        if registered_with is not None:
            _query_params.append(("registered_with", registered_with))

        if filter is not None:
            _query_params.append(("filter", filter))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # authentication setting
        _auth_settings: list[str] = ["ApiKeyAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/system_profile/sap_sids",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_system_profile_get_sap_system(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SystemProfileSapSystemOut:
        """get all sap system values and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_system_profile_get_sap_system_with_http_info(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SystemProfileSapSystemOut]:
        """get all sap system values and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_system_profile_get_sap_system_without_preload_content(
        self,
        tags: Annotated[
            list[Annotated[str, Field(strict=True)]] | None,
            Field(description="filters out hosts not tagged by the given tags"),
        ] = None,
        per_page: Annotated[
            Annotated[int, Field(le=100, strict=True, ge=1)] | None,
            Field(description="A number of items to return per page."),
        ] = None,
        page: Annotated[
            Annotated[int, Field(le=21474837, strict=True, ge=1)] | None,
            Field(description="A page number of the items to return."),
        ] = None,
        staleness: Annotated[
            list[StrictStr] | None,
            Field(
                description="Culling states of the hosts. Default: fresh, stale and stale_warning"
            ),
        ] = None,
        registered_with: Annotated[
            list[StrictStr] | None,
            Field(description="Filters out any host not registered by the specified reporters"),
        ] = None,
        filter: Annotated[
            dict[str, dict[str, SystemProfileNestedObjectValue | None]] | None,
            Field(
                description='Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"workloads": {"sap": {"sap_system": {"eq": "true"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][sap_system][eq]=true" <br /><br /> To get "edge" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"host_type": {"eq": "edge"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][host_type][eq]=edge" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{"system_profile": {"operating_system": {"name": {"eq": "rhel"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;"?filter[system_profile][name][eq]=rhel"'
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get all sap system values and counts on the account

        Required permissions: inventory:hosts:read

        :param tags: filters out hosts not tagged by the given tags
        :type tags: List[str]
        :param per_page: A number of items to return per page.
        :type per_page: int
        :param page: A page number of the items to return.
        :type page: int
        :param staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :type staleness: List[str]
        :param registered_with: Filters out any host not registered by the specified reporters
        :type registered_with: List[str]
        :param filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :type filter: Dict[str, SystemProfileNestedObjectValue]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_get_sap_system_serialize(
            tags=tags,
            per_page=per_page,
            page=page,
            staleness=staleness,
            registered_with=registered_with,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "SystemProfileSapSystemOut",
            "400": None,
            "404": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _api_system_profile_get_sap_system_serialize(
        self,
        tags,
        per_page,
        page,
        staleness,
        registered_with,
        filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
            "tags": "multi",
            "staleness": "multi",
            "registered_with": "multi",
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[str, str | bytes] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if tags is not None:
            _query_params.append(("tags", tags))

        if per_page is not None:
            _query_params.append(("per_page", per_page))

        if page is not None:
            _query_params.append(("page", page))

        if staleness is not None:
            _query_params.append(("staleness", staleness))

        if registered_with is not None:
            _query_params.append(("registered_with", registered_with))

        if filter is not None:
            _query_params.append(("filter", filter))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # authentication setting
        _auth_settings: list[str] = ["ApiKeyAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/system_profile/sap_system",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_system_profile_validate_schema(
        self,
        repo_branch: Annotated[
            StrictStr, Field(description="The branch of the inventory-schemas repo to use")
        ],
        repo_fork: Annotated[
            StrictStr | None, Field(description="The fork of the inventory-schemas repo to use")
        ] = None,
        days: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="How many days worth of data to validate"),
        ] = None,
        max_messages: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="Stops polling when this number of messages has been collected"),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """validate system profile schema

        Validates System Profile data from recent Kafka messages against a given spec, and compares it with the current one. Only HBI Admins can access this endpoint.

        :param repo_branch: The branch of the inventory-schemas repo to use (required)
        :type repo_branch: str
        :param repo_fork: The fork of the inventory-schemas repo to use
        :type repo_fork: str
        :param days: How many days worth of data to validate
        :type days: int
        :param max_messages: Stops polling when this number of messages has been collected
        :type max_messages: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_validate_schema_serialize(
            repo_branch=repo_branch,
            repo_fork=repo_fork,
            days=days,
            max_messages=max_messages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": None,
            "403": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_system_profile_validate_schema_with_http_info(
        self,
        repo_branch: Annotated[
            StrictStr, Field(description="The branch of the inventory-schemas repo to use")
        ],
        repo_fork: Annotated[
            StrictStr | None, Field(description="The fork of the inventory-schemas repo to use")
        ] = None,
        days: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="How many days worth of data to validate"),
        ] = None,
        max_messages: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="Stops polling when this number of messages has been collected"),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """validate system profile schema

        Validates System Profile data from recent Kafka messages against a given spec, and compares it with the current one. Only HBI Admins can access this endpoint.

        :param repo_branch: The branch of the inventory-schemas repo to use (required)
        :type repo_branch: str
        :param repo_fork: The fork of the inventory-schemas repo to use
        :type repo_fork: str
        :param days: How many days worth of data to validate
        :type days: int
        :param max_messages: Stops polling when this number of messages has been collected
        :type max_messages: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_validate_schema_serialize(
            repo_branch=repo_branch,
            repo_fork=repo_fork,
            days=days,
            max_messages=max_messages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": None,
            "403": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_system_profile_validate_schema_without_preload_content(
        self,
        repo_branch: Annotated[
            StrictStr, Field(description="The branch of the inventory-schemas repo to use")
        ],
        repo_fork: Annotated[
            StrictStr | None, Field(description="The fork of the inventory-schemas repo to use")
        ] = None,
        days: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="How many days worth of data to validate"),
        ] = None,
        max_messages: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(description="Stops polling when this number of messages has been collected"),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """validate system profile schema

        Validates System Profile data from recent Kafka messages against a given spec, and compares it with the current one. Only HBI Admins can access this endpoint.

        :param repo_branch: The branch of the inventory-schemas repo to use (required)
        :type repo_branch: str
        :param repo_fork: The fork of the inventory-schemas repo to use
        :type repo_fork: str
        :param days: How many days worth of data to validate
        :type days: int
        :param max_messages: Stops polling when this number of messages has been collected
        :type max_messages: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._api_system_profile_validate_schema_serialize(
            repo_branch=repo_branch,
            repo_fork=repo_fork,
            days=days,
            max_messages=max_messages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": None,
            "403": None,
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _api_system_profile_validate_schema_serialize(
        self,
        repo_branch,
        repo_fork,
        days,
        max_messages,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {}

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[str, str | bytes] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if repo_fork is not None:
            _query_params.append(("repo_fork", repo_fork))

        if repo_branch is not None:
            _query_params.append(("repo_branch", repo_branch))

        if days is not None:
            _query_params.append(("days", days))

        if max_messages is not None:
            _query_params.append(("max_messages", max_messages))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # authentication setting
        _auth_settings: list[str] = ["ApiKeyAuth"]

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/system_profile/validate_schema",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
