{
 "title": "Inventory",
 "tags": [
  "platform-health",
  "inventory"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_appsre", "label": "Datasource - App SRE", "query": "prometheus" },
   {
    "name": "kibana",
    "query": "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto"
   },
   {
    "name": "kibana_dev",
    "query": "https://kibana-kibana.5a9f.insights-dev.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:d2da0310-7048-11e9-a501-7998195d35a8,interval:auto"
   },
   {
    "name": "kibana_prod",
    "query": "https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Inventory API</h1></center>"
   },
   "content": "<center><h1>Inventory API</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h1>Inventory SLIs</h1></center>"
   },
   "content": "<center><h1>Inventory API</h1></center>"
  },
  {
   "title": "API Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{service=\"host-inventory-service\"})"
    }
   ]
  },
  {
   "title": "API restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=~\"host-inventory-service.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\"}[$__range])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hosts deleted (API)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_delete_host_count_total{service=~\"host-inventory-service.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5XX errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\", status=~\"5.*\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Messages Consumed in last 5 minutes",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(aws_kafka_sum_offset_lag_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latency (3scale)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"inventory\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"4xx\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\", status=~\"4.*\"}[$__range])) OR vector(0)) / sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Hosts deleted (reaper)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(sum(inventory_delete_host_count_total{exported_job=~\"inventory-reaper-host-inventory-stage|inventory-reaper-host-inventory-prod\"})[$__range:59m])"
    }
   ]
  },
  {
   "title": "parser validation errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_parsing_failures_total{cause=\"invalid\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Syndication Failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(hosts_syndication_fail_count_total{exported_job=~\"hosts-syndicator-host-inventory-.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"5xx\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\", status=~\"5.*\"}[$__range])) OR vector(0)) / sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reaper failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_reaper_fail_count_total{exported_job=~\"inventory-reaper-host-inventory-stage|inventory-reaper-host-inventory-prod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "ingress consumer lag (ingress)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_kafka_sum_offset_lag_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "3scale API Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(inventory_http_request_total{service=~\"host-inventory-service.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"inventory\"}[1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 10 },
   "options": {
    "content": "<center><h1>Inventory MQ Service</h1></center>"
   },
   "content": "<center><h1>Inventory MQ Service</h1></center>"
  },
  {
   "title": "parser failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_parsing_failures_total{cause=\"error\", kubernetes_namespace='host-inventory-$namespace'}[$__range])) OR vector(0)"
    }
   ]
  },
  {
   "title": "MQ Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{service=~\"host-inventory-mq-.*\"})"
    }
   ]
  },
  {
   "title": "MQ restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=~\"host-inventory-mq-.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "underreplicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{topic=~\"platform.inventory.host-ingress.*\"})"
    }
   ]
  },
  {
   "title": "parser validation errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_parsing_failures_total{cause=\"invalid\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Host ingress stats",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_add_host_successes_total{result=\"created\"}[$__range])) by (reporter) > 0",
     "legendFormat": "added"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_successes_total{result=\"updated\"}[$__range])) by (reporter) > 0",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"ValidationException\"}[$__range])) by (reporter)"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"ValidationException\"}[$__range])) by (reporter) / (sum(increase(inventory_ingress_add_host_failures_total[$__range])) by (reporter) + sum(increase(inventory_ingress_add_host_successes_total[$__range])) by (reporter)) "
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"InventoryException\"}[$__range])) by (reporter)"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"InventoryException\"}[$__range])) by (reporter) / (sum(increase(inventory_ingress_add_host_failures_total[$__range])) by (reporter) + sum(increase(inventory_ingress_add_host_successes_total[$__range])) by (reporter)) "
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"Exception\"}[$__range])) by (reporter)"
    }
   ]
  },
  {
   "title": "Latency (3scale)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"inventory\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Incoming byte rate (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_in_per_sec_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_out_per_sec_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ingress consumer lag (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_kafka_sum_offset_lag_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "consumed message rate (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(aws_kafka_sum_offset_lag_average{topic=~'(platform-mq-stage.|platform-mq-prod)?platform.inventory.host-ingress.*'}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "produce failure ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 32 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_produce_large_message_failures_total[$__range])) / sum(increase(inventory_event_producer_failures[$__range]))"
    }
   ]
  },
  {
   "title": "Maximum message sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(inventory_consumed_message_size_sum[$__rate_interval]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "max(rate(inventory_produced_message_size_sum[$__rate_interval]))",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Host delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts deleted (API)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(inventory_delete_host_count_total[1m])) by (deployment)",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Hosts deleted (reaper)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "inventory_delete_host_count_total{exported_job=~\"inventory-reaper-host-inventory-stage|inventory-reaper-host-inventory-prod\"}",
       "legendFormat": "{{exported_job}}"
      }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Latency (API)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(inventory_http_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency (Outbound requests)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(inventory_outbound_http_response_time_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "5xx per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"5xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Message handler failures per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_handler_failures_total[1m])) by (deploymentconfig)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{service=\"host-inventory-service\"})",
     "legendFormat": "number of pods"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\nlabel_replace(\nup{service=~\"host-inventory-mq-.*\"},\n\"deployment\", \"$1\", \"pod\", \"^host-inventory-mq-(.*?)-.*$\"\n)\n) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"host-inventory-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"host-inventory-mq-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"host-inventory-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"host-inventory-mq-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}