{
 "title": "ConsoleDot MSK Stage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ingress consumer lag (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_kafka_sum_offset_lag_average{cluster_name='consoledot-stage', consumer_group='inventory-mq', topic=~'platform.inventory.host-ingress.*'} ) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "AWS Kafka Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_in_per_sec_sum{cluster_name='consoledot-stage', topic=~'platform.inventory.host-ingress.*'}) by (broker_id)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_kafka_cpu_system_sum{cluster_name=\"consoledot-stage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_global_partition_count_sum{cluster_name=\"consoledot-stage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_kafka_under_replicated_partitions_sum{cluster_name=\"consoledot-stage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_offline_partitions_count_sum{cluster_name=\"consoledot-stage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_kafka_memory_used_sum{cluster_name=\"consoledot-stage\"}",
       "legendFormat": "Broker {{broker_id}}"
      }
     ]
    },
    {
     "title": "CPU Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_cpu_user_sum{cluster_name=\"consoledot-stage\"}",
       "legendFormat": "Broker {{broker_id}} %User"
      },
      {
       "expr": "aws_kafka_cpu_system_sum{cluster_name=\"consoledot-stage\"}",
       "legendFormat": "Broker {{broker_id}} %System"
      }
     ]
    },
    {
     "title": "Disk Usage per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_kafka_kafka_data_logs_disk_used_sum{cluster_name=\"consoledot-stage\"}",
       "legendFormat": "Logs Dir Used Broker {{broker_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(aws_kafka_bytes_in_per_sec_sum{cluster_name=\"consoledot-stage\"}) by (broker_id)",
       "legendFormat": "Ingress Broker {{broker_id}}"
      },
      {
       "expr": "sum(aws_kafka_bytes_out_per_sec_sum{cluster_name=\"consoledot-stage\"}) by (broker_id)",
       "legendFormat": "Egress Broker {{broker_id}}"
      }
     ]
    },
    {
     "title": "Zookeeper Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(aws_kafka_zoo_keeper_request_latency_ms_mean_sum{cluster_name=\"consoledot-stage\"}) by (broker_id)",
       "legendFormat": "Broker {{broker_id}} Latency"
      }
     ]
    }
   ]
  },
  { "title": "Lag Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Consumer Lag by Group",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(aws_kafka_max_offset_lag_maximum{cluster_name=\"consoledot-stage\", consumer_group!~\".*amazon.*\"}) by (consumer_group, topic)",
     "legendFormat": "{{topic}} -- Group {{consumer_group}}"
    }
   ]
  }
 ]
}