#  duplicate-hosts-removeris run manually to synchronize host-invnenotry DB
# to the xjoin elastic-search index.

# To delete duplicate hosts, set the value for metadata.name and run :
# "kubectl create -f duplicate_remover_clowd_job_invocation.yaml"

apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdJobInvocation
metadata:
  name: duplicate-hosts-remover-job-name
spec:
  appName: host-inventory
  jobs:
    - duplicate_hosts_remover
