# duplicate-hosts-remover is run manually to detect and delete
# duplicate hosts from the database.

# To delete duplicate hosts, replace the value of metadata.name
# with the name of the Job in the namespace and run:
# "kubectl create -f duplicate_remover_clowd_job_invocation.yaml"

apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdJobInvocation
metadata:
  name: duplicate-hosts-remover-job-name
spec:
  appName: host-inventory
  jobs:
    - duplicate-hosts-remover
