# Host synchronizer is run manually to synchronize host-invnenotry DB
# to the xjoin elastic-search index.

# To synchronize hosts, set the value for metadata.name and run :
# "kubectl create -f synchronizer_clowd_job_invocation.yaml"

apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdJobInvocation
metadata:
  name: synch-job-name
spec:
  appName: host-inventory
  jobs:
    - synchronizer
