"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401

# python 2 and python 3 compatibility library
from iqe_host_inventory_api.api_client import ApiClient
from iqe_host_inventory_api.exceptions import ApiTypeError
from iqe_host_inventory_api.exceptions import ApiValueError


class HostsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_host_delete_all_hosts(self, **kwargs):
        """Delete all hosts on the account  # noqa: E501

        Delete all hosts on the account.  The request must include \"confirm_delete_all=true\". <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_all_hosts(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param bool confirm_delete_all: Confirmation to delete all hosts on the account
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_delete_all_hosts_with_http_info(**kwargs)

    def api_host_delete_all_hosts_with_http_info(self, **kwargs):
        """Delete all hosts on the account  # noqa: E501

        Delete all hosts on the account.  The request must include \"confirm_delete_all=true\". <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_all_hosts_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param bool confirm_delete_all: Confirmation to delete all hosts on the account
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["confirm_delete_all"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_delete_all_hosts"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []
        if (
            "confirm_delete_all" in local_var_params
            and local_var_params["confirm_delete_all"] is not None
        ):
            query_params.append(("confirm_delete_all", local_var_params["confirm_delete_all"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/all",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_delete_host_by_id(self, host_id_list, **kwargs):
        """Delete hosts by IDs  # noqa: E501

        Delete hosts by IDs <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_host_by_id(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str branch_id: Filter by branch_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_delete_host_by_id_with_http_info(host_id_list, **kwargs)

    def api_host_delete_host_by_id_with_http_info(self, host_id_list, **kwargs):
        """Delete hosts by IDs  # noqa: E501

        Delete hosts by IDs <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_host_by_id_with_http_info(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str branch_id: Filter by branch_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "branch_id"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_delete_host_by_id"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_delete_host_by_id`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_delete_hosts_by_filter(self, **kwargs):
        """Delete the entire list of hosts filtered by the given parameters  # noqa: E501

        Delete the entire list of hosts filtered by the given parameters. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_hosts_by_filter(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str display_name: Filter by display_name (case-insensitive)
        :param str fqdn: Filter by FQDN (case-insensitive)
        :param str hostname_or_id: Filter by display_name, fqdn, id (case-insensitive)
        :param str insights_id: Filter by insights_id
        :param str provider_id: Filter by provider_id
        :param str provider_type: Filter by provider_type
        :param datetime updated_start: Only show hosts last modified after the given date
        :param datetime updated_end: Only show hosts last modified before the given date
        :param datetime last_check_in_start: Only show hosts last checked in after the given date
        :param datetime last_check_in_end: Only show hosts last checked in before the given date
        :param list[str] group_name: Filter by group name
        :param list[str] group_id: Filter by group ID (UUID format)
        :param list[str] registered_with: Filters out any host not registered by the specified reporters
        :param list[str] system_type: Filters systems by type
        :param list[str] staleness: Culling states of the hosts.
        :param list[str] tags: filters out hosts not tagged by the given tags
        :param dict(str, object) filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :param str subscription_manager_id: Filter by subscription_manager_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_delete_hosts_by_filter_with_http_info(**kwargs)

    def api_host_delete_hosts_by_filter_with_http_info(self, **kwargs):
        """Delete the entire list of hosts filtered by the given parameters  # noqa: E501

        Delete the entire list of hosts filtered by the given parameters. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_delete_hosts_by_filter_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str display_name: Filter by display_name (case-insensitive)
        :param str fqdn: Filter by FQDN (case-insensitive)
        :param str hostname_or_id: Filter by display_name, fqdn, id (case-insensitive)
        :param str insights_id: Filter by insights_id
        :param str provider_id: Filter by provider_id
        :param str provider_type: Filter by provider_type
        :param datetime updated_start: Only show hosts last modified after the given date
        :param datetime updated_end: Only show hosts last modified before the given date
        :param datetime last_check_in_start: Only show hosts last checked in after the given date
        :param datetime last_check_in_end: Only show hosts last checked in before the given date
        :param list[str] group_name: Filter by group name
        :param list[str] group_id: Filter by group ID (UUID format)
        :param list[str] registered_with: Filters out any host not registered by the specified reporters
        :param list[str] system_type: Filters systems by type
        :param list[str] staleness: Culling states of the hosts.
        :param list[str] tags: filters out hosts not tagged by the given tags
        :param dict(str, object) filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :param str subscription_manager_id: Filter by subscription_manager_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            "display_name",
            "fqdn",
            "hostname_or_id",
            "insights_id",
            "provider_id",
            "provider_type",
            "updated_start",
            "updated_end",
            "last_check_in_start",
            "last_check_in_end",
            "group_name",
            "group_id",
            "registered_with",
            "system_type",
            "staleness",
            "tags",
            "filter",
            "subscription_manager_id",
        ]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_delete_hosts_by_filter"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []
        if "display_name" in local_var_params and local_var_params["display_name"] is not None:
            query_params.append(("display_name", local_var_params["display_name"]))
        if "fqdn" in local_var_params and local_var_params["fqdn"] is not None:
            query_params.append(("fqdn", local_var_params["fqdn"]))
        if "hostname_or_id" in local_var_params and local_var_params["hostname_or_id"] is not None:
            query_params.append(("hostname_or_id", local_var_params["hostname_or_id"]))
        if "insights_id" in local_var_params and local_var_params["insights_id"] is not None:
            query_params.append(("insights_id", local_var_params["insights_id"]))
        if "provider_id" in local_var_params and local_var_params["provider_id"] is not None:
            query_params.append(("provider_id", local_var_params["provider_id"]))
        if "provider_type" in local_var_params and local_var_params["provider_type"] is not None:
            query_params.append(("provider_type", local_var_params["provider_type"]))
        if "updated_start" in local_var_params and local_var_params["updated_start"] is not None:
            query_params.append(("updated_start", local_var_params["updated_start"]))
        if "updated_end" in local_var_params and local_var_params["updated_end"] is not None:
            query_params.append(("updated_end", local_var_params["updated_end"]))
        if (
            "last_check_in_start" in local_var_params
            and local_var_params["last_check_in_start"] is not None
        ):
            query_params.append(("last_check_in_start", local_var_params["last_check_in_start"]))
        if (
            "last_check_in_end" in local_var_params
            and local_var_params["last_check_in_end"] is not None
        ):
            query_params.append(("last_check_in_end", local_var_params["last_check_in_end"]))
        if "group_name" in local_var_params and local_var_params["group_name"] is not None:
            query_params.append(("group_name", local_var_params["group_name"]))
            collection_formats["group_name"] = "multi"
        if "group_id" in local_var_params and local_var_params["group_id"] is not None:
            query_params.append(("group_id", local_var_params["group_id"]))
            collection_formats["group_id"] = "multi"
        if (
            "registered_with" in local_var_params
            and local_var_params["registered_with"] is not None
        ):
            query_params.append(("registered_with", local_var_params["registered_with"]))
            collection_formats["registered_with"] = "multi"
        if "system_type" in local_var_params and local_var_params["system_type"] is not None:
            query_params.append(("system_type", local_var_params["system_type"]))
            collection_formats["system_type"] = "multi"
        if "staleness" in local_var_params and local_var_params["staleness"] is not None:
            query_params.append(("staleness", local_var_params["staleness"]))
            collection_formats["staleness"] = "multi"
        if "tags" in local_var_params and local_var_params["tags"] is not None:
            query_params.append(("tags", local_var_params["tags"]))
            collection_formats["tags"] = "multi"
        if "filter" in local_var_params and local_var_params["filter"] is not None:
            query_params.append(("filter", local_var_params["filter"]))
        if (
            "subscription_manager_id" in local_var_params
            and local_var_params["subscription_manager_id"] is not None
        ):
            query_params.append((
                "subscription_manager_id",
                local_var_params["subscription_manager_id"],
            ))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_by_id(self, host_id_list, **kwargs):
        """Find hosts by their IDs  # noqa: E501

        Find one or more hosts by their ID. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_by_id(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str branch_id: Filter by branch_id
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: HostQueryOutput
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_by_id_with_http_info(host_id_list, **kwargs)

    def api_host_get_host_by_id_with_http_info(self, host_id_list, **kwargs):
        """Find hosts by their IDs  # noqa: E501

        Find one or more hosts by their ID. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_by_id_with_http_info(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str branch_id: Filter by branch_id
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(HostQueryOutput, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            "host_id_list",
            "branch_id",
            "per_page",
            "page",
            "order_by",
            "order_how",
            "fields",
        ]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_get_host_by_id"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_get_host_by_id`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))
        if "per_page" in local_var_params and local_var_params["per_page"] is not None:
            query_params.append(("per_page", local_var_params["per_page"]))
        if "page" in local_var_params and local_var_params["page"] is not None:
            query_params.append(("page", local_var_params["page"]))
        if "order_by" in local_var_params and local_var_params["order_by"] is not None:
            query_params.append(("order_by", local_var_params["order_by"]))
        if "order_how" in local_var_params and local_var_params["order_how"] is not None:
            query_params.append(("order_how", local_var_params["order_how"]))
        if "fields" in local_var_params and local_var_params["fields"] is not None:
            query_params.append(("fields", local_var_params["fields"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="HostQueryOutput",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_exists(self, **kwargs):
        """Find one host by insights_id, if it exists  # noqa: E501

        Find one host by insights_id, if it exists. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_exists(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str insights_id: Filter by insights_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: HostIdOut
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_exists_with_http_info(**kwargs)

    def api_host_get_host_exists_with_http_info(self, **kwargs):
        """Find one host by insights_id, if it exists  # noqa: E501

        Find one host by insights_id, if it exists. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_exists_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str insights_id: Filter by insights_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(HostIdOut, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["insights_id"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_get_host_exists"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []
        if "insights_id" in local_var_params and local_var_params["insights_id"] is not None:
            query_params.append(("insights_id", local_var_params["insights_id"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/host_exists",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="HostIdOut",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_list(self, **kwargs):
        """Read the entire list of hosts  # noqa: E501

        Read the entire list of all hosts available to the account. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str display_name: Filter by display_name (case-insensitive)
        :param str fqdn: Filter by FQDN (case-insensitive)
        :param str hostname_or_id: Filter by display_name, fqdn, id (case-insensitive)
        :param str insights_id: Filter by insights_id
        :param str subscription_manager_id: Filter by subscription_manager_id
        :param str provider_id: Filter by provider_id
        :param str provider_type: Filter by provider_type
        :param datetime updated_start: Only show hosts last modified after the given date
        :param datetime updated_end: Only show hosts last modified before the given date
        :param datetime last_check_in_start: Only show hosts last checked in after the given date
        :param datetime last_check_in_end: Only show hosts last checked in before the given date
        :param list[str] group_name: Filter by group name
        :param list[str] group_id: Filter by group ID (UUID format)
        :param str branch_id: Filter by branch_id
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param list[str] staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :param list[str] tags: filters out hosts not tagged by the given tags
        :param list[str] registered_with: Filters out any host not registered by the specified reporters
        :param list[str] system_type: Filters systems by type
        :param dict(str, object) filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: HostQueryOutput
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_list_with_http_info(**kwargs)

    def api_host_get_host_list_with_http_info(self, **kwargs):
        """Read the entire list of hosts  # noqa: E501

        Read the entire list of all hosts available to the account. <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str display_name: Filter by display_name (case-insensitive)
        :param str fqdn: Filter by FQDN (case-insensitive)
        :param str hostname_or_id: Filter by display_name, fqdn, id (case-insensitive)
        :param str insights_id: Filter by insights_id
        :param str subscription_manager_id: Filter by subscription_manager_id
        :param str provider_id: Filter by provider_id
        :param str provider_type: Filter by provider_type
        :param datetime updated_start: Only show hosts last modified after the given date
        :param datetime updated_end: Only show hosts last modified before the given date
        :param datetime last_check_in_start: Only show hosts last checked in after the given date
        :param datetime last_check_in_end: Only show hosts last checked in before the given date
        :param list[str] group_name: Filter by group name
        :param list[str] group_id: Filter by group ID (UUID format)
        :param str branch_id: Filter by branch_id
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param list[str] staleness: Culling states of the hosts. Default: fresh, stale and stale_warning
        :param list[str] tags: filters out hosts not tagged by the given tags
        :param list[str] registered_with: Filters out any host not registered by the specified reporters
        :param list[str] system_type: Filters systems by type
        :param dict(str, object) filter: Filters hosts based on system_profile fields. For example: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"workloads\": {\"sap\": {\"sap_system\": {\"eq\": \"true\"}}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][sap_system][eq]=true\" <br /><br /> To get \"edge\" hosts, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"host_type\": {\"eq\": \"edge\"}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][host_type][eq]=edge\" <br /><br /> To get hosts with an specific operating system, use this explicit filter: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": {\"operating_system\": {\"name\": {\"eq\": \"rhel\"}}}} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?filter[system_profile][name][eq]=rhel\"
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(HostQueryOutput, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            "display_name",
            "fqdn",
            "hostname_or_id",
            "insights_id",
            "subscription_manager_id",
            "provider_id",
            "provider_type",
            "updated_start",
            "updated_end",
            "last_check_in_start",
            "last_check_in_end",
            "group_name",
            "group_id",
            "branch_id",
            "per_page",
            "page",
            "order_by",
            "order_how",
            "staleness",
            "tags",
            "registered_with",
            "system_type",
            "filter",
            "fields",
        ]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_get_host_list"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]

        collection_formats = {}

        path_params = {}

        query_params = []
        if "display_name" in local_var_params and local_var_params["display_name"] is not None:
            query_params.append(("display_name", local_var_params["display_name"]))
        if "fqdn" in local_var_params and local_var_params["fqdn"] is not None:
            query_params.append(("fqdn", local_var_params["fqdn"]))
        if "hostname_or_id" in local_var_params and local_var_params["hostname_or_id"] is not None:
            query_params.append(("hostname_or_id", local_var_params["hostname_or_id"]))
        if "insights_id" in local_var_params and local_var_params["insights_id"] is not None:
            query_params.append(("insights_id", local_var_params["insights_id"]))
        if (
            "subscription_manager_id" in local_var_params
            and local_var_params["subscription_manager_id"] is not None
        ):
            query_params.append((
                "subscription_manager_id",
                local_var_params["subscription_manager_id"],
            ))
        if "provider_id" in local_var_params and local_var_params["provider_id"] is not None:
            query_params.append(("provider_id", local_var_params["provider_id"]))
        if "provider_type" in local_var_params and local_var_params["provider_type"] is not None:
            query_params.append(("provider_type", local_var_params["provider_type"]))
        if "updated_start" in local_var_params and local_var_params["updated_start"] is not None:
            query_params.append(("updated_start", local_var_params["updated_start"]))
        if "updated_end" in local_var_params and local_var_params["updated_end"] is not None:
            query_params.append(("updated_end", local_var_params["updated_end"]))
        if (
            "last_check_in_start" in local_var_params
            and local_var_params["last_check_in_start"] is not None
        ):
            query_params.append(("last_check_in_start", local_var_params["last_check_in_start"]))
        if (
            "last_check_in_end" in local_var_params
            and local_var_params["last_check_in_end"] is not None
        ):
            query_params.append(("last_check_in_end", local_var_params["last_check_in_end"]))
        if "group_name" in local_var_params and local_var_params["group_name"] is not None:
            query_params.append(("group_name", local_var_params["group_name"]))
            collection_formats["group_name"] = "multi"
        if "group_id" in local_var_params and local_var_params["group_id"] is not None:
            query_params.append(("group_id", local_var_params["group_id"]))
            collection_formats["group_id"] = "multi"
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))
        if "per_page" in local_var_params and local_var_params["per_page"] is not None:
            query_params.append(("per_page", local_var_params["per_page"]))
        if "page" in local_var_params and local_var_params["page"] is not None:
            query_params.append(("page", local_var_params["page"]))
        if "order_by" in local_var_params and local_var_params["order_by"] is not None:
            query_params.append(("order_by", local_var_params["order_by"]))
        if "order_how" in local_var_params and local_var_params["order_how"] is not None:
            query_params.append(("order_how", local_var_params["order_how"]))
        if "staleness" in local_var_params and local_var_params["staleness"] is not None:
            query_params.append(("staleness", local_var_params["staleness"]))
            collection_formats["staleness"] = "multi"
        if "tags" in local_var_params and local_var_params["tags"] is not None:
            query_params.append(("tags", local_var_params["tags"]))
            collection_formats["tags"] = "multi"
        if (
            "registered_with" in local_var_params
            and local_var_params["registered_with"] is not None
        ):
            query_params.append(("registered_with", local_var_params["registered_with"]))
            collection_formats["registered_with"] = "multi"
        if "system_type" in local_var_params and local_var_params["system_type"] is not None:
            query_params.append(("system_type", local_var_params["system_type"]))
            collection_formats["system_type"] = "multi"
        if "filter" in local_var_params and local_var_params["filter"] is not None:
            query_params.append(("filter", local_var_params["filter"]))
        if "fields" in local_var_params and local_var_params["fields"] is not None:
            query_params.append(("fields", local_var_params["fields"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="HostQueryOutput",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_system_profile_by_id(self, host_id_list, **kwargs):
        """Return one or more hosts system profile  # noqa: E501

        Find one or more hosts by their ID and return the id and system profile <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_system_profile_by_id(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param str branch_id: Filter by branch_id
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: SystemProfileByHostOut
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_system_profile_by_id_with_http_info(host_id_list, **kwargs)

    def api_host_get_host_system_profile_by_id_with_http_info(self, host_id_list, **kwargs):
        """Return one or more hosts system profile  # noqa: E501

        Find one or more hosts by their ID and return the id and system profile <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_system_profile_by_id_with_http_info(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param str branch_id: Filter by branch_id
        :param dict(str, object) fields: Fetches only mentioned system_profile fields. For example, <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;{\"system_profile\": [\"arch\", \"host_type\"]} <br /><br /> which equates to the URL param: <br /><br /> &nbsp;&nbsp;&nbsp;&nbsp;\"?fields[system_profile]=arch,host_type\"
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(SystemProfileByHostOut, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            "host_id_list",
            "per_page",
            "page",
            "order_by",
            "order_how",
            "branch_id",
            "fields",
        ]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_get_host_system_profile_by_id"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_get_host_system_profile_by_id`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "per_page" in local_var_params and local_var_params["per_page"] is not None:
            query_params.append(("per_page", local_var_params["per_page"]))
        if "page" in local_var_params and local_var_params["page"] is not None:
            query_params.append(("page", local_var_params["page"]))
        if "order_by" in local_var_params and local_var_params["order_by"] is not None:
            query_params.append(("order_by", local_var_params["order_by"]))
        if "order_how" in local_var_params and local_var_params["order_how"] is not None:
            query_params.append(("order_how", local_var_params["order_how"]))
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))
        if "fields" in local_var_params and local_var_params["fields"] is not None:
            query_params.append(("fields", local_var_params["fields"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}/system_profile",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="SystemProfileByHostOut",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_tag_count(self, host_id_list, **kwargs):
        """Get the number of tags on a host or hosts  # noqa: E501

        Get the number of tags on a host or hosts <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_tag_count(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: TagCountOut
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_tag_count_with_http_info(host_id_list, **kwargs)

    def api_host_get_host_tag_count_with_http_info(self, host_id_list, **kwargs):
        """Get the number of tags on a host or hosts  # noqa: E501

        Get the number of tags on a host or hosts <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_tag_count_with_http_info(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(TagCountOut, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "per_page", "page", "order_by", "order_how"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_get_host_tag_count"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_get_host_tag_count`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "per_page" in local_var_params and local_var_params["per_page"] is not None:
            query_params.append(("per_page", local_var_params["per_page"]))
        if "page" in local_var_params and local_var_params["page"] is not None:
            query_params.append(("page", local_var_params["page"]))
        if "order_by" in local_var_params and local_var_params["order_by"] is not None:
            query_params.append(("order_by", local_var_params["order_by"]))
        if "order_how" in local_var_params and local_var_params["order_how"] is not None:
            query_params.append(("order_how", local_var_params["order_how"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}/tags/count",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="TagCountOut",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_get_host_tags(self, host_id_list, **kwargs):
        """Get the tags on a host  # noqa: E501

        Get the tags on a host <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_tags(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param str search: Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: TagsOut
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_get_host_tags_with_http_info(host_id_list, **kwargs)

    def api_host_get_host_tags_with_http_info(self, host_id_list, **kwargs):
        """Get the tags on a host  # noqa: E501

        Get the tags on a host <br /><br /> Required permissions: inventory:hosts:read  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_get_host_tags_with_http_info(host_id_list, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param int per_page: A number of items to return per page.
        :param int page: A page number of the items to return.
        :param str order_by: Ordering field name
        :param str order_how: Direction of the ordering (case-insensitive); defaults to ASC for display_name, and to DESC for updated and operating_system
        :param str search: Used for searching tags and sap_sids that match the given search string. For searching tags, a tag's namespace, key, and/or value is used for matching.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(TagsOut, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "per_page", "page", "order_by", "order_how", "search"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_get_host_tags"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_get_host_tags`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "per_page" in local_var_params and local_var_params["per_page"] is not None:
            query_params.append(("per_page", local_var_params["per_page"]))
        if "page" in local_var_params and local_var_params["page"] is not None:
            query_params.append(("page", local_var_params["page"]))
        if "order_by" in local_var_params and local_var_params["order_by"] is not None:
            query_params.append(("order_by", local_var_params["order_by"]))
        if "order_how" in local_var_params and local_var_params["order_how"] is not None:
            query_params.append(("order_how", local_var_params["order_how"]))
        if "search" in local_var_params and local_var_params["search"] is not None:
            query_params.append(("search", local_var_params["search"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}/tags",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="TagsOut",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_host_checkin(self, create_check_in, **kwargs):
        """Update staleness timestamps for a host matching the provided facts  # noqa: E501

        Finds a host and updates its staleness timestamps. It uses the supplied canonical facts to determine which host to update. By default, the staleness timestamp is set to 1 hour from when the request is received; however, this can be overridden by supplying the interval. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_host_checkin(create_check_in, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param CreateCheckIn create_check_in: Data required to create a check-in record for a host. (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: HostOut
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_host_checkin_with_http_info(create_check_in, **kwargs)

    def api_host_host_checkin_with_http_info(self, create_check_in, **kwargs):
        """Update staleness timestamps for a host matching the provided facts  # noqa: E501

        Finds a host and updates its staleness timestamps. It uses the supplied canonical facts to determine which host to update. By default, the staleness timestamp is set to 1 hour from when the request is received; however, this can be overridden by supplying the interval. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_host_checkin_with_http_info(create_check_in, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param CreateCheckIn create_check_in: Data required to create a check-in record for a host. (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(HostOut, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["create_check_in"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_host_checkin"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'create_check_in' is set
        if self.api_client.client_side_validation and (
            "create_check_in" not in local_var_params
            or local_var_params["create_check_in"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `create_check_in` when calling `api_host_host_checkin`"
            )

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "create_check_in" in local_var_params:
            body_params = local_var_params["create_check_in"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type([
            "application/json"
        ])

        # Authentication setting
        auth_settings = ["ApiKeyAuth", "BearerAuth"]

        return self.api_client.call_api(
            "/hosts/checkin",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="HostOut",
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_merge_facts(self, host_id_list, namespace, body, **kwargs):
        """Merge facts under a namespace  # noqa: E501

        Merge one or multiple hosts facts under a namespace. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_merge_facts(host_id_list, namespace, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str namespace: A namespace of the merged facts. (required)
        :param object body: A dictionary with the new facts to merge with the original ones. (required)
        :param str branch_id: Filter by branch_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_merge_facts_with_http_info(host_id_list, namespace, body, **kwargs)

    def api_host_merge_facts_with_http_info(self, host_id_list, namespace, body, **kwargs):
        """Merge facts under a namespace  # noqa: E501

        Merge one or multiple hosts facts under a namespace. <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_merge_facts_with_http_info(host_id_list, namespace, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str namespace: A namespace of the merged facts. (required)
        :param object body: A dictionary with the new facts to merge with the original ones. (required)
        :param str branch_id: Filter by branch_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "namespace", "body", "branch_id"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_merge_facts"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_merge_facts`"
            )
        # verify the required parameter 'namespace' is set
        if self.api_client.client_side_validation and (
            "namespace" not in local_var_params or local_var_params["namespace"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `namespace` when calling `api_host_merge_facts`"
            )
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and (
            "body" not in local_var_params or local_var_params["body"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `body` when calling `api_host_merge_facts`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"
        if "namespace" in local_var_params:
            path_params["namespace"] = local_var_params["namespace"]

        query_params = []
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in local_var_params:
            body_params = local_var_params["body"]
        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type([
            "application/json"
        ])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}/facts/{namespace}",
            "PATCH",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_patch_host_by_id(self, host_id_list, patch_host_in, **kwargs):
        """Update hosts  # noqa: E501

        Update hosts <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_patch_host_by_id(host_id_list, patch_host_in, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param PatchHostIn patch_host_in: A group of fields to be updated on the hosts (required)
        :param str branch_id: Filter by branch_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_patch_host_by_id_with_http_info(host_id_list, patch_host_in, **kwargs)

    def api_host_patch_host_by_id_with_http_info(self, host_id_list, patch_host_in, **kwargs):
        """Update hosts  # noqa: E501

        Update hosts <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_patch_host_by_id_with_http_info(host_id_list, patch_host_in, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param PatchHostIn patch_host_in: A group of fields to be updated on the hosts (required)
        :param str branch_id: Filter by branch_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "patch_host_in", "branch_id"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method api_host_patch_host_by_id"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_patch_host_by_id`"
            )
        # verify the required parameter 'patch_host_in' is set
        if self.api_client.client_side_validation and (
            "patch_host_in" not in local_var_params or local_var_params["patch_host_in"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `patch_host_in` when calling `api_host_patch_host_by_id`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"

        query_params = []
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "patch_host_in" in local_var_params:
            body_params = local_var_params["patch_host_in"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type([
            "application/json"
        ])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}",
            "PATCH",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def api_host_replace_facts(self, host_id_list, namespace, body, **kwargs):
        """Replace facts under a namespace  # noqa: E501

        Replace facts under a namespace <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_replace_facts(host_id_list, namespace, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str namespace: A namespace of the merged facts. (required)
        :param object body: A dictionary with the new facts to replace the original ones. (required)
        :param str branch_id: Filter by branch_id
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        return self.api_host_replace_facts_with_http_info(host_id_list, namespace, body, **kwargs)

    def api_host_replace_facts_with_http_info(self, host_id_list, namespace, body, **kwargs):
        """Replace facts under a namespace  # noqa: E501

        Replace facts under a namespace <br /><br /> Required permissions: inventory:hosts:write  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_host_replace_facts_with_http_info(host_id_list, namespace, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param list[str] host_id_list: A comma-separated list of host IDs. (required)
        :param str namespace: A namespace of the merged facts. (required)
        :param object body: A dictionary with the new facts to replace the original ones. (required)
        :param str branch_id: Filter by branch_id
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ["host_id_list", "namespace", "body", "branch_id"]
        all_params.extend([
            "async_req",
            "_return_http_data_only",
            "_preload_content",
            "_request_timeout",
        ])

        for key, val in local_var_params["kwargs"].items():
            if key not in all_params:
                raise ApiTypeError(
                    f"Got an unexpected keyword argument '{key}' to method api_host_replace_facts"
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'host_id_list' is set
        if self.api_client.client_side_validation and (
            "host_id_list" not in local_var_params or local_var_params["host_id_list"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `host_id_list` when calling `api_host_replace_facts`"
            )
        # verify the required parameter 'namespace' is set
        if self.api_client.client_side_validation and (
            "namespace" not in local_var_params or local_var_params["namespace"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `namespace` when calling `api_host_replace_facts`"
            )
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and (
            "body" not in local_var_params or local_var_params["body"] is None
        ):
            raise ApiValueError(
                "Missing the required parameter `body` when calling `api_host_replace_facts`"
            )

        collection_formats = {}

        path_params = {}
        if "host_id_list" in local_var_params:
            path_params["host_id_list"] = local_var_params["host_id_list"]
            collection_formats["host_id_list"] = "csv"
        if "namespace" in local_var_params:
            path_params["namespace"] = local_var_params["namespace"]

        query_params = []
        if "branch_id" in local_var_params and local_var_params["branch_id"] is not None:
            query_params.append(("branch_id", local_var_params["branch_id"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in local_var_params:
            body_params = local_var_params["body"]
        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type([
            "application/json"
        ])

        # Authentication setting
        auth_settings = ["ApiKeyAuth"]

        return self.api_client.call_api(
            "/hosts/{host_id_list}/facts/{namespace}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
