#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ -f "$REPO_ROOT/.git" ]]; then
    MAIN_REPO_ROOT=$(git -C "$REPO_ROOT" rev-parse --path-format=absolute --git-common-dir | sed 's|/\.git$||')
else
    MAIN_REPO_ROOT="$REPO_ROOT"
fi

WORKTREES_DIR="$MAIN_REPO_ROOT/worktrees"
MAX_SLOTS=8

# --- Utility Functions ---

sanitize_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's|/|-|g; s|[^a-z0-9_-]||g'
}

find_free_slot() {
    local used_slots=()
    for env_file in "$WORKTREES_DIR"/*/.env; do
        [[ -f "$env_file" ]] || continue
        local db_port
        db_port=$(grep '^INVENTORY_DB_PORT=' "$env_file" | cut -d= -f2)
        if [[ -n "$db_port" ]]; then
            local slot=$(( (db_port - 5432) / 100 ))
            used_slots+=("$slot")
        fi
    done

    for slot in $(seq 1 $MAX_SLOTS); do
        local in_use=false
        for used in "${used_slots[@]+"${used_slots[@]}"}"; do
            if [[ "$used" == "$slot" ]]; then
                in_use=true
                break
            fi
        done
        if [[ "$in_use" == "false" ]]; then
            echo "$slot"
            return 0
        fi
    done

    return 1
}

generate_env() {
    local safe_name="$1"
    local slot="$2"
    local wt_dir="$WORKTREES_DIR/$safe_name"
    local offset=$((slot * 100))

    local db_port=$((5432 + offset))
    local web_port=$((8080 + offset))
    local kafka_port=$((9092 + offset))
    local kafka_internal_port=$((29092 + offset))
    local redis_port=$((6379 + offset))
    local unleash_port=$((4242 + offset))
    local grafana_port=$((3000 + offset))
    local tempo_otlp_port=$((4318 + offset))
    local tempo_internal_port=$((3250 + offset))
    local minio_api_port=$((9099 + offset))
    local minio_console_port=$((9991 + offset))
    local export_port=$((8001 + offset))
    local export_metrics_port=$((9090 + offset))
    local export_private_port=$((10010 + offset))
    local prom_gw_port=$((9091 + offset))

    cat > "$wt_dir/.env" << EOF
# Worktree: $safe_name (slot $slot)
# Auto-generated by scripts/worktree.sh — do not edit manually
COMPOSE_PROJECT_NAME=hbi-$safe_name
HBI_PG_DATA=$HOME/.pg_data_$safe_name

# Host port mappings (slot $slot, offset +$offset)
INVENTORY_DB_PORT=$db_port
HBI_WEB_PORT=$web_port
HBI_KAFKA_PORT=$kafka_port
HBI_KAFKA_INTERNAL_PORT=$kafka_internal_port
HBI_REDIS_PORT=$redis_port
HBI_UNLEASH_PORT=$unleash_port
HBI_GRAFANA_PORT=$grafana_port
HBI_TEMPO_OTLP_PORT=$tempo_otlp_port
HBI_TEMPO_INTERNAL_PORT=$tempo_internal_port
HBI_MINIO_API_PORT=$minio_api_port
HBI_MINIO_CONSOLE_PORT=$minio_console_port
HBI_EXPORT_PORT=$export_port
HBI_EXPORT_METRICS_PORT=$export_metrics_port
HBI_EXPORT_PRIVATE_PORT=$export_private_port
HBI_PROM_GW_PORT=$prom_gw_port

# App/test configuration
PROMETHEUS_MULTIPROC_DIR=/tmp
BYPASS_RBAC=true
BYPASS_UNLEASH=true
BYPASS_KESSEL=true
APP_NAME=inventory
INVENTORY_DB_USER=insights
INVENTORY_DB_PASS=insights
INVENTORY_DB_HOST=localhost
INVENTORY_DB_NAME=insights
INVENTORY_DB_POOL_TIMEOUT=5
INVENTORY_DB_POOL_SIZE=5
INVENTORY_DB_SSL_MODE=""
INVENTORY_DB_SSL_CERT=""
UNLEASH_CACHE_DIR=./.unleash
UNLEASH_URL=http://localhost:$unleash_port/api
KAFKA_BOOTSTRAP_SERVERS=localhost:$kafka_internal_port
KAFKA_EXPORT_SERVICE_TOPIC=platform.export.requests
CACHE_PORT=$redis_port
PROMETHEUS_PUSHGATEWAY=localhost:$prom_gw_port
EXPORT_SERVICE_ENDPOINT=http://localhost:$export_private_port
EOF

    local main_env="$MAIN_REPO_ROOT/.env"
    if [[ -f "$main_env" ]]; then
        local token
        token=$(grep '^UNLEASH_TOKEN=' "$main_env" | head -1)
        if [[ -n "$token" ]]; then
            echo "$token" >> "$wt_dir/.env"
        fi
    fi
}

remove_pg_data() {
    local pg_data="$1"
    if [[ -d "$pg_data" ]]; then
        echo "Removing DB data at $pg_data..."
        podman unshare rm -rf "$pg_data" 2>/dev/null || rm -rf "$pg_data"
    fi
}

resolve_worktree() {
    local name="${1:-}"
    if [[ -n "$name" ]]; then
        local wt_dir="$WORKTREES_DIR/$name"
        if [[ ! -d "$wt_dir" ]]; then
            echo "Error: Worktree '$name' not found at $wt_dir" >&2
            exit 1
        fi
        echo "$wt_dir"
    else
        local cwd
        cwd=$(pwd)
        if [[ "$cwd" == "$WORKTREES_DIR"/* ]]; then
            local relative="${cwd#"$WORKTREES_DIR"/}"
            local wt_name="${relative%%/*}"
            echo "$WORKTREES_DIR/$wt_name"
        else
            echo "Error: Not inside a worktree directory and no name provided" >&2
            exit 1
        fi
    fi
}

is_stack_running() {
    local wt_dir="$1"
    (
        cd "$wt_dir"
        podman compose -f dev.yml ps -q 2>/dev/null | grep -q .
    )
}

wait_for_db() {
    local db_port="$1"
    local max_attempts=30
    local attempt=0
    echo "Waiting for DB on port $db_port..."
    while ! pg_isready -h localhost -p "$db_port" -q 2>/dev/null; do
        attempt=$((attempt + 1))
        if [[ $attempt -ge $max_attempts ]]; then
            echo "Error: DB did not become healthy after $max_attempts attempts" >&2
            return 1
        fi
        sleep 2
    done
    echo "DB is ready."
}

run_migrations() {
    local wt_dir="$1"
    local db_port="$2"
    cd "$wt_dir"
    INVENTORY_DB_HOST=localhost \
    INVENTORY_DB_PORT="$db_port" \
    INVENTORY_DB_NAME=insights \
    INVENTORY_DB_USER=insights \
    INVENTORY_DB_PASS=insights \
    uv run make upgrade_db
}

# --- Command stubs (implemented in subsequent tasks) ---

cmd_create() {
    local skip_iqe=false
    local branch_name=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --no-iqe) skip_iqe=true; shift ;;
            *) branch_name="$1"; shift ;;
        esac
    done

    if [[ -z "$branch_name" ]]; then
        echo "Usage: worktree.sh create [--no-iqe] <branch-name>" >&2
        exit 1
    fi

    local safe_name
    safe_name=$(sanitize_name "$branch_name")

    if [[ -d "$WORKTREES_DIR/$safe_name" ]]; then
        echo "Error: Worktree '$safe_name' already exists at $WORKTREES_DIR/$safe_name" >&2
        exit 1
    fi

    local slot
    slot=$(find_free_slot) || {
        echo "Error: All $MAX_SLOTS worktree slots are in use. Active worktrees:" >&2
        cmd_list >&2
        exit 1
    }

    local offset=$((slot * 100))
    echo "Creating worktree '$safe_name' on branch '$branch_name' (slot $slot, port offset +$offset)..."

    mkdir -p "$WORKTREES_DIR"
    git worktree add "$WORKTREES_DIR/$safe_name" -b "$branch_name"

    echo "Initializing submodules..."
    git -C "$WORKTREES_DIR/$safe_name" submodule update --init --recursive

    generate_env "$safe_name" "$slot"

    local pg_data
    pg_data=$(grep '^HBI_PG_DATA=' "$WORKTREES_DIR/$safe_name/.env" | cut -d= -f2)
    pg_data="${pg_data/#\~/$HOME}"
    mkdir -p "$pg_data"

    echo "Installing virtual environments..."
    local main_log="$WORKTREES_DIR/$safe_name/.uv-main.log"
    local main_pid

    (
        cd "$WORKTREES_DIR/$safe_name"
        uv sync --frozen
    ) > "$main_log" 2>&1 &
    main_pid=$!
    echo "  Main venv (PID $main_pid) — log: $main_log"

    local iqe_pid=""
    if [[ "$skip_iqe" == "false" ]]; then
        local iqe_log="$WORKTREES_DIR/$safe_name/.uv-iqe.log"
        (
            cd "$WORKTREES_DIR/$safe_name"
            uv --project iqe-host-inventory-plugin sync --frozen
        ) > "$iqe_log" 2>&1 &
        iqe_pid=$!
        echo "  IQE venv  (PID $iqe_pid) — log: $iqe_log"
    else
        echo "  IQE venv skipped (--no-iqe)"
    fi

    local failed=false
    if ! wait "$main_pid"; then
        echo "Error: Main venv installation failed. See $main_log" >&2
        failed=true
    else
        echo "  Main venv installed successfully."
    fi
    if [[ -n "$iqe_pid" ]]; then
        if ! wait "$iqe_pid"; then
            echo "Error: IQE venv installation failed. See $iqe_log" >&2
            failed=true
        else
            echo "  IQE venv installed successfully."
        fi
    fi

    if [[ "$failed" == "true" ]]; then
        echo "" >&2
        if [[ -f "$main_log" ]]; then
            echo "── Last 20 lines of main venv log ──" >&2
            tail -20 "$main_log" >&2
        fi
        local iqe_log="$WORKTREES_DIR/$safe_name/.uv-iqe.log"
        if [[ -f "$iqe_log" ]]; then
            echo "── Last 20 lines of IQE venv log ──" >&2
            tail -20 "$iqe_log" >&2
        fi
        echo "" >&2
        echo "Cleaning up after venv failure..." >&2
        remove_pg_data "$pg_data"
        cd "$MAIN_REPO_ROOT"
        git worktree remove "$WORKTREES_DIR/$safe_name" --force 2>/dev/null || true
        git branch -D "$branch_name" 2>/dev/null || true
        exit 1
    fi

    rm -f "$main_log" "$WORKTREES_DIR/$safe_name/.uv-iqe.log" "$WORKTREES_DIR/$safe_name/.uv-main.log"

    echo "Starting compose stack..."
    cd "$WORKTREES_DIR/$safe_name"
    if ! podman compose -f dev.yml up -d; then
        echo "Error: Compose stack failed to start. Cleaning up..." >&2
        remove_pg_data "$pg_data"
        rm -rf "$WORKTREES_DIR/$safe_name/.venv"
        if [[ "$skip_iqe" == "false" ]]; then
            rm -rf "$WORKTREES_DIR/$safe_name/iqe-host-inventory-plugin/.venv"
        fi
        cd "$MAIN_REPO_ROOT"
        git worktree remove "$WORKTREES_DIR/$safe_name" --force 2>/dev/null || true
        git branch -D "$branch_name" 2>/dev/null || true
        exit 1
    fi

    local db_port
    db_port=$(grep '^INVENTORY_DB_PORT=' "$WORKTREES_DIR/$safe_name/.env" | cut -d= -f2)
    wait_for_db "$db_port"

    echo "Running database migrations..."
    if ! run_migrations "$WORKTREES_DIR/$safe_name" "$db_port"; then
        echo "Error: DB migration failed. Stack left running for debugging." >&2
        echo "  DB Port: $db_port" >&2
        echo "  Path:    $WORKTREES_DIR/$safe_name" >&2
        exit 1
    fi

    local web_port
    web_port=$(grep '^HBI_WEB_PORT=' "$WORKTREES_DIR/$safe_name/.env" | cut -d= -f2)

    echo ""
    echo "════════════════════════════════════════════════════"
    echo " Worktree '$safe_name' created successfully!"
    echo "════════════════════════════════════════════════════"
    echo "  Branch:     $branch_name"
    echo "  Path:       $WORKTREES_DIR/$safe_name"
    echo "  Slot:       $slot"
    echo "  Web API:    http://localhost:$web_port"
    echo "  DB Port:    $db_port"
    echo ""
    echo "To activate the main app environment:"
    echo "  cd $WORKTREES_DIR/$safe_name && source .venv/bin/activate"
    if [[ "$skip_iqe" == "false" ]]; then
        echo ""
        echo "To activate the IQE test environment:"
        echo "  cd $WORKTREES_DIR/$safe_name && source iqe-host-inventory-plugin/.venv/bin/activate"
    fi
    echo "════════════════════════════════════════════════════"
}
cmd_up() {
    local clean=false
    local name=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --clean) clean=true; shift ;;
            *) name="$1"; shift ;;
        esac
    done

    local wt_dir
    wt_dir=$(resolve_worktree "$name")
    local wt_name
    wt_name=$(basename "$wt_dir")

    if is_stack_running "$wt_dir" && [[ "$clean" == "false" ]]; then
        local web_port
        web_port=$(grep '^HBI_WEB_PORT=' "$wt_dir/.env" | cut -d= -f2)
        local db_port
        db_port=$(grep '^INVENTORY_DB_PORT=' "$wt_dir/.env" | cut -d= -f2)
        echo "Stack for '$wt_name' is already running."
        echo "  Web API:   http://localhost:$web_port"
        echo "  DB Port:   $db_port"
        echo ""
        echo "Use --clean to tear down and restart with a fresh database."
        echo ""
        echo "To activate the main app environment:"
        echo "  cd $wt_dir && source .venv/bin/activate"
        if [[ -d "$wt_dir/iqe-host-inventory-plugin/.venv" ]]; then
            echo ""
            echo "To activate the IQE test environment:"
            echo "  cd $wt_dir && source iqe-host-inventory-plugin/.venv/bin/activate"
        fi
        exit 0
    fi

    if [[ "$clean" == "true" ]]; then
        echo "Cleaning and restarting stack for '$wt_name'..."
        cd "$wt_dir"
        podman compose -f dev.yml down 2>/dev/null || true
        local pg_data
        pg_data=$(grep '^HBI_PG_DATA=' "$wt_dir/.env" | cut -d= -f2)
        pg_data="${pg_data/#\~/$HOME}"
        remove_pg_data "$pg_data"
        mkdir -p "$pg_data"
    fi

    echo "Starting stack for '$wt_name'..."
    cd "$wt_dir"
    podman compose -f dev.yml up -d

    local db_port
    db_port=$(grep '^INVENTORY_DB_PORT=' "$wt_dir/.env" | cut -d= -f2)
    wait_for_db "$db_port"

    echo "Running database migrations..."
    run_migrations "$wt_dir" "$db_port"

    local web_port
    web_port=$(grep '^HBI_WEB_PORT=' "$wt_dir/.env" | cut -d= -f2)

    echo ""
    echo "Stack for '$wt_name' is up."
    echo "  Web API:   http://localhost:$web_port"
    echo "  DB Port:   $db_port"
    echo ""
    echo "To activate the main app environment:"
    echo "  cd $wt_dir && source .venv/bin/activate"
    if [[ -d "$wt_dir/iqe-host-inventory-plugin/.venv" ]]; then
        echo ""
        echo "To activate the IQE test environment:"
        echo "  cd $wt_dir && source iqe-host-inventory-plugin/.venv/bin/activate"
    fi
}
cmd_down() {
    local keep_db=false
    local name=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --keep-db) keep_db=true; shift ;;
            *) name="$1"; shift ;;
        esac
    done

    local wt_dir
    wt_dir=$(resolve_worktree "$name")
    local wt_name
    wt_name=$(basename "$wt_dir")

    echo "Stopping stack for '$wt_name'..."
    cd "$wt_dir"
    podman compose -f dev.yml down

    if [[ "$keep_db" == "false" ]]; then
        local pg_data
        pg_data=$(grep '^HBI_PG_DATA=' "$wt_dir/.env" | cut -d= -f2)
        pg_data="${pg_data/#\~/$HOME}"
        remove_pg_data "$pg_data"
    else
        echo "DB data preserved (--keep-db)."
    fi

    echo "Stack for '$wt_name' stopped."
}
cmd_destroy() {
    local name="${1:?Usage: worktree.sh destroy <worktree-name>}"
    local wt_dir="$WORKTREES_DIR/$name"

    if [[ ! -d "$wt_dir" ]]; then
        echo "Error: Worktree '$name' not found at $wt_dir" >&2
        exit 1
    fi

    echo "Destroying worktree '$name'..."

    if [[ -f "$wt_dir/.env" ]]; then
        if is_stack_running "$wt_dir" 2>/dev/null; then
            echo "Stopping compose stack..."
            cd "$wt_dir"
            podman compose -f dev.yml down 2>/dev/null || true
        fi

        local pg_data
        pg_data=$(grep '^HBI_PG_DATA=' "$wt_dir/.env" | cut -d= -f2)
        pg_data="${pg_data/#\~/$HOME}"
        remove_pg_data "$pg_data"
    fi

    echo "Removing virtual environments..."
    rm -rf "$wt_dir/.venv"
    rm -rf "$wt_dir/iqe-host-inventory-plugin/.venv"

    local branch
    branch=$(git -C "$wt_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

    cd "$MAIN_REPO_ROOT"
    echo "Removing git worktree..."
    git worktree remove "$wt_dir" --force

    if [[ -n "$branch" ]]; then
        if git branch -d "$branch" 2>/dev/null; then
            echo "Deleted branch '$branch' (was fully merged)."
        else
            echo "Warning: Branch '$branch' is not fully merged. Not deleted."
            echo "  To force delete: git branch -D $branch"
        fi
    fi

    echo ""
    echo "Worktree '$name' destroyed."
}
cmd_list() {
    printf "\nHBI Worktrees:\n"
    echo "─────────────────────────────────────────────────────────────────────────────"
    printf "%-20s %-25s %-6s %-10s %-8s %-8s\n" "NAME" "BRANCH" "SLOT" "STATUS" "WEB" "DB"
    echo "─────────────────────────────────────────────────────────────────────────────"

    local found=false
    for env_file in "$WORKTREES_DIR"/*/.env; do
        [[ -f "$env_file" ]] || continue
        found=true

        local wt_dir
        wt_dir=$(dirname "$env_file")
        local wt_name
        wt_name=$(basename "$wt_dir")

        local branch
        branch=$(git -C "$wt_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

        local db_port
        db_port=$(grep '^INVENTORY_DB_PORT=' "$env_file" | cut -d= -f2)
        local web_port
        web_port=$(grep '^HBI_WEB_PORT=' "$env_file" | cut -d= -f2)
        local slot=$(( (db_port - 5432) / 100 ))

        local status="stopped"
        if is_stack_running "$wt_dir" 2>/dev/null; then
            status="running"
        fi

        printf "%-20s %-25s %-6s %-10s %-8s %-8s\n" "$wt_name" "$branch" "$slot" "$status" "$web_port" "$db_port"
    done

    if [[ "$found" == "false" ]]; then
        echo "  (no worktrees)"
    fi

    echo "─────────────────────────────────────────────────────────────────────────────"
    echo ""
}

# --- Main dispatch ---

case "${1:-}" in
    create)  shift; cmd_create "$@" ;;
    up)      shift; cmd_up "$@" ;;
    down)    shift; cmd_down "$@" ;;
    destroy) shift; cmd_destroy "$@" ;;
    list)    shift; cmd_list "$@" ;;
    *)
        echo "Usage: worktree.sh <command> [args]"
        echo ""
        echo "Commands:"
        echo "  create [--no-iqe] <branch-name>   Create a new worktree with full isolation"
        echo "  up [worktree-name] [--clean]       Start compose stack for a worktree"
        echo "  down [worktree-name] [--keep-db]   Stop compose stack"
        echo "  destroy <worktree-name>            Remove worktree and all resources"
        echo "  list                               Show all worktrees and their status"
        exit 1
        ;;
esac
