"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class CanonicalFactsOut:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "insights_id": "str",
        "subscription_manager_id": "str",
        "satellite_id": "str",
        "bios_uuid": "str",
        "ip_addresses": "list[str]",
        "fqdn": "str",
        "mac_addresses": "list[str]",
        "provider_id": "str",
        "provider_type": "str",
    }

    attribute_map = {
        "insights_id": "insights_id",
        "subscription_manager_id": "subscription_manager_id",
        "satellite_id": "satellite_id",
        "bios_uuid": "bios_uuid",
        "ip_addresses": "ip_addresses",
        "fqdn": "fqdn",
        "mac_addresses": "mac_addresses",
        "provider_id": "provider_id",
        "provider_type": "provider_type",
    }

    def __init__(
        self,
        insights_id=None,
        subscription_manager_id=None,
        satellite_id=None,
        bios_uuid=None,
        ip_addresses=None,
        fqdn=None,
        mac_addresses=None,
        provider_id=None,
        provider_type=None,
        local_vars_configuration=None,
    ):
        """CanonicalFactsOut - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._insights_id = None
        self._subscription_manager_id = None
        self._satellite_id = None
        self._bios_uuid = None
        self._ip_addresses = None
        self._fqdn = None
        self._mac_addresses = None
        self._provider_id = None
        self._provider_type = None
        self.discriminator = None

        self.insights_id = insights_id
        self.subscription_manager_id = subscription_manager_id
        self.satellite_id = satellite_id
        self.bios_uuid = bios_uuid
        self.ip_addresses = ip_addresses
        self.fqdn = fqdn
        self.mac_addresses = mac_addresses
        self.provider_id = provider_id
        self.provider_type = provider_type

    @property
    def insights_id(self):
        """Gets the insights_id of this CanonicalFactsOut.  # noqa: E501

        An ID defined in /etc/insights-client/machine-id. This field is considered a canonical fact.  # noqa: E501

        :return: The insights_id of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._insights_id

    @insights_id.setter
    def insights_id(self, insights_id):
        """Sets the insights_id of this CanonicalFactsOut.

        An ID defined in /etc/insights-client/machine-id. This field is considered a canonical fact.  # noqa: E501

        :param insights_id: The insights_id of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._insights_id = insights_id

    @property
    def subscription_manager_id(self):
        """Gets the subscription_manager_id of this CanonicalFactsOut.  # noqa: E501

        A Red Hat Subcription Manager ID of a RHEL host.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The subscription_manager_id of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._subscription_manager_id

    @subscription_manager_id.setter
    def subscription_manager_id(self, subscription_manager_id):
        """Sets the subscription_manager_id of this CanonicalFactsOut.

        A Red Hat Subcription Manager ID of a RHEL host.  This field is considered to be a canonical fact.  # noqa: E501

        :param subscription_manager_id: The subscription_manager_id of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._subscription_manager_id = subscription_manager_id

    @property
    def satellite_id(self):
        """Gets the satellite_id of this CanonicalFactsOut.  # noqa: E501

        A Red Hat Satellite ID of a RHEL host.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The satellite_id of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._satellite_id

    @satellite_id.setter
    def satellite_id(self, satellite_id):
        """Sets the satellite_id of this CanonicalFactsOut.

        A Red Hat Satellite ID of a RHEL host.  This field is considered to be a canonical fact.  # noqa: E501

        :param satellite_id: The satellite_id of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._satellite_id = satellite_id

    @property
    def bios_uuid(self):
        """Gets the bios_uuid of this CanonicalFactsOut.  # noqa: E501

        A UUID of the host machine BIOS.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The bios_uuid of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._bios_uuid

    @bios_uuid.setter
    def bios_uuid(self, bios_uuid):
        """Sets the bios_uuid of this CanonicalFactsOut.

        A UUID of the host machine BIOS.  This field is considered to be a canonical fact.  # noqa: E501

        :param bios_uuid: The bios_uuid of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._bios_uuid = bios_uuid

    @property
    def ip_addresses(self):
        """Gets the ip_addresses of this CanonicalFactsOut.  # noqa: E501

        Host’s network IP addresses.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The ip_addresses of this CanonicalFactsOut.  # noqa: E501
        :rtype: list[str]
        """
        return self._ip_addresses

    @ip_addresses.setter
    def ip_addresses(self, ip_addresses):
        """Sets the ip_addresses of this CanonicalFactsOut.

        Host’s network IP addresses.  This field is considered to be a canonical fact.  # noqa: E501

        :param ip_addresses: The ip_addresses of this CanonicalFactsOut.  # noqa: E501
        :type: list[str]
        """

        self._ip_addresses = ip_addresses

    @property
    def fqdn(self):
        """Gets the fqdn of this CanonicalFactsOut.  # noqa: E501

        A host’s Fully Qualified Domain Name.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The fqdn of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn):
        """Sets the fqdn of this CanonicalFactsOut.

        A host’s Fully Qualified Domain Name.  This field is considered to be a canonical fact.  # noqa: E501

        :param fqdn: The fqdn of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._fqdn = fqdn

    @property
    def mac_addresses(self):
        """Gets the mac_addresses of this CanonicalFactsOut.  # noqa: E501

        Host’s network interfaces MAC addresses.  This field is considered to be a canonical fact.  # noqa: E501

        :return: The mac_addresses of this CanonicalFactsOut.  # noqa: E501
        :rtype: list[str]
        """
        return self._mac_addresses

    @mac_addresses.setter
    def mac_addresses(self, mac_addresses):
        """Sets the mac_addresses of this CanonicalFactsOut.

        Host’s network interfaces MAC addresses.  This field is considered to be a canonical fact.  # noqa: E501

        :param mac_addresses: The mac_addresses of this CanonicalFactsOut.  # noqa: E501
        :type: list[str]
        """

        self._mac_addresses = mac_addresses

    @property
    def provider_id(self):
        """Gets the provider_id of this CanonicalFactsOut.  # noqa: E501

        Host’s reference in the external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM etc. This field is one of the canonical facts and does not work without provider_type.  # noqa: E501

        :return: The provider_id of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id):
        """Sets the provider_id of this CanonicalFactsOut.

        Host’s reference in the external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM etc. This field is one of the canonical facts and does not work without provider_type.  # noqa: E501

        :param provider_id: The provider_id of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._provider_id = provider_id

    @property
    def provider_type(self):
        """Gets the provider_type of this CanonicalFactsOut.  # noqa: E501

        Type of external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM, etc. This field is one of the canonical facts and does not workout provider_id.  # noqa: E501

        :return: The provider_type of this CanonicalFactsOut.  # noqa: E501
        :rtype: str
        """
        return self._provider_type

    @provider_type.setter
    def provider_type(self, provider_type):
        """Sets the provider_type of this CanonicalFactsOut.

        Type of external source e.g. Alibaba, AWS EC2, Azure, GCP, IBM, etc. This field is one of the canonical facts and does not workout provider_id.  # noqa: E501

        :param provider_type: The provider_type of this CanonicalFactsOut.  # noqa: E501
        :type: str
        """

        self._provider_type = provider_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CanonicalFactsOut):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CanonicalFactsOut):
            return True

        return self.to_dict() != other.to_dict()
