"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class ComplianceAppData:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"policies": "list[object]", "last_scan": "datetime"}

    attribute_map = {"policies": "policies", "last_scan": "last_scan"}

    def __init__(self, policies=None, last_scan=None, local_vars_configuration=None):
        """ComplianceAppData - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._policies = None
        self._last_scan = None
        self.discriminator = None

        self.policies = policies
        self.last_scan = last_scan

    @property
    def policies(self):
        """Gets the policies of this ComplianceAppData.  # noqa: E501


        :return: The policies of this ComplianceAppData.  # noqa: E501
        :rtype: list[object]
        """
        return self._policies

    @policies.setter
    def policies(self, policies):
        """Sets the policies of this ComplianceAppData.


        :param policies: The policies of this ComplianceAppData.  # noqa: E501
        :type: list[object]
        """

        self._policies = policies

    @property
    def last_scan(self):
        """Gets the last_scan of this ComplianceAppData.  # noqa: E501


        :return: The last_scan of this ComplianceAppData.  # noqa: E501
        :rtype: datetime
        """
        return self._last_scan

    @last_scan.setter
    def last_scan(self, last_scan):
        """Sets the last_scan of this ComplianceAppData.


        :param last_scan: The last_scan of this ComplianceAppData.  # noqa: E501
        :type: datetime
        """

        self._last_scan = last_scan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComplianceAppData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComplianceAppData):
            return True

        return self.to_dict() != other.to_dict()
