"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class ConsumerApplicationsData:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "advisor": "AdvisorAppData",
        "vulnerability": "VulnerabilityAppData",
        "patch": "PatchAppData",
        "remediations": "RemediationsAppData",
        "compliance": "ComplianceAppData",
        "malware": "MalwareAppData",
    }

    attribute_map = {
        "advisor": "advisor",
        "vulnerability": "vulnerability",
        "patch": "patch",
        "remediations": "remediations",
        "compliance": "compliance",
        "malware": "malware",
    }

    def __init__(
        self,
        advisor=None,
        vulnerability=None,
        patch=None,
        remediations=None,
        compliance=None,
        malware=None,
        local_vars_configuration=None,
    ):
        """ConsumerApplicationsData - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._advisor = None
        self._vulnerability = None
        self._patch = None
        self._remediations = None
        self._compliance = None
        self._malware = None
        self.discriminator = None

        if advisor is not None:
            self.advisor = advisor
        if vulnerability is not None:
            self.vulnerability = vulnerability
        if patch is not None:
            self.patch = patch
        if remediations is not None:
            self.remediations = remediations
        if compliance is not None:
            self.compliance = compliance
        if malware is not None:
            self.malware = malware

    @property
    def advisor(self):
        """Gets the advisor of this ConsumerApplicationsData.  # noqa: E501


        :return: The advisor of this ConsumerApplicationsData.  # noqa: E501
        :rtype: AdvisorAppData
        """
        return self._advisor

    @advisor.setter
    def advisor(self, advisor):
        """Sets the advisor of this ConsumerApplicationsData.


        :param advisor: The advisor of this ConsumerApplicationsData.  # noqa: E501
        :type: AdvisorAppData
        """

        self._advisor = advisor

    @property
    def vulnerability(self):
        """Gets the vulnerability of this ConsumerApplicationsData.  # noqa: E501


        :return: The vulnerability of this ConsumerApplicationsData.  # noqa: E501
        :rtype: VulnerabilityAppData
        """
        return self._vulnerability

    @vulnerability.setter
    def vulnerability(self, vulnerability):
        """Sets the vulnerability of this ConsumerApplicationsData.


        :param vulnerability: The vulnerability of this ConsumerApplicationsData.  # noqa: E501
        :type: VulnerabilityAppData
        """

        self._vulnerability = vulnerability

    @property
    def patch(self):
        """Gets the patch of this ConsumerApplicationsData.  # noqa: E501


        :return: The patch of this ConsumerApplicationsData.  # noqa: E501
        :rtype: PatchAppData
        """
        return self._patch

    @patch.setter
    def patch(self, patch):
        """Sets the patch of this ConsumerApplicationsData.


        :param patch: The patch of this ConsumerApplicationsData.  # noqa: E501
        :type: PatchAppData
        """

        self._patch = patch

    @property
    def remediations(self):
        """Gets the remediations of this ConsumerApplicationsData.  # noqa: E501


        :return: The remediations of this ConsumerApplicationsData.  # noqa: E501
        :rtype: RemediationsAppData
        """
        return self._remediations

    @remediations.setter
    def remediations(self, remediations):
        """Sets the remediations of this ConsumerApplicationsData.


        :param remediations: The remediations of this ConsumerApplicationsData.  # noqa: E501
        :type: RemediationsAppData
        """

        self._remediations = remediations

    @property
    def compliance(self):
        """Gets the compliance of this ConsumerApplicationsData.  # noqa: E501


        :return: The compliance of this ConsumerApplicationsData.  # noqa: E501
        :rtype: ComplianceAppData
        """
        return self._compliance

    @compliance.setter
    def compliance(self, compliance):
        """Sets the compliance of this ConsumerApplicationsData.


        :param compliance: The compliance of this ConsumerApplicationsData.  # noqa: E501
        :type: ComplianceAppData
        """

        self._compliance = compliance

    @property
    def malware(self):
        """Gets the malware of this ConsumerApplicationsData.  # noqa: E501


        :return: The malware of this ConsumerApplicationsData.  # noqa: E501
        :rtype: MalwareAppData
        """
        return self._malware

    @malware.setter
    def malware(self, malware):
        """Sets the malware of this ConsumerApplicationsData.


        :param malware: The malware of this ConsumerApplicationsData.  # noqa: E501
        :type: MalwareAppData
        """

        self._malware = malware

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConsumerApplicationsData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConsumerApplicationsData):
            return True

        return self.to_dict() != other.to_dict()
