"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class GroupIn:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"name": "str", "host_ids": "list[str]"}

    attribute_map = {"name": "name", "host_ids": "host_ids"}

    def __init__(self, name=None, host_ids=None, local_vars_configuration=None):
        """GroupIn - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._host_ids = None
        self.discriminator = None

        if name is not None:
            self.name = name
        self.host_ids = host_ids

    @property
    def name(self):
        """Gets the name of this GroupIn.  # noqa: E501

        A group’s human-readable name.  # noqa: E501

        :return: The name of this GroupIn.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GroupIn.

        A group’s human-readable name.  # noqa: E501

        :param name: The name of this GroupIn.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def host_ids(self):
        """Gets the host_ids of this GroupIn.  # noqa: E501

        A comma-separated list of host IDs that belong to the group.  # noqa: E501

        :return: The host_ids of this GroupIn.  # noqa: E501
        :rtype: list[str]
        """
        return self._host_ids

    @host_ids.setter
    def host_ids(self, host_ids):
        """Sets the host_ids of this GroupIn.

        A comma-separated list of host IDs that belong to the group.  # noqa: E501

        :param host_ids: The host_ids of this GroupIn.  # noqa: E501
        :type: list[str]
        """

        self._host_ids = host_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupIn):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupIn):
            return True

        return self.to_dict() != other.to_dict()
