"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re

from iqe_host_inventory_api.configuration import Configuration


class GroupOut:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "id": "str",
        "name": "str",
        "account": "str",
        "org_id": "str",
        "ungrouped": "bool",
        "created": "datetime",
        "updated": "datetime",
    }

    attribute_map = {
        "id": "id",
        "name": "name",
        "account": "account",
        "org_id": "org_id",
        "ungrouped": "ungrouped",
        "created": "created",
        "updated": "updated",
    }

    def __init__(
        self,
        id=None,
        name=None,
        account=None,
        org_id=None,
        ungrouped=None,
        created=None,
        updated=None,
        local_vars_configuration=None,
    ):
        """GroupOut - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._account = None
        self._org_id = None
        self._ungrouped = None
        self._created = None
        self._updated = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        self.account = account
        if org_id is not None:
            self.org_id = org_id
        if ungrouped is not None:
            self.ungrouped = ungrouped
        if created is not None:
            self.created = created
        if updated is not None:
            self.updated = updated

    @property
    def id(self):
        """Gets the id of this GroupOut.  # noqa: E501


        :return: The id of this GroupOut.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GroupOut.


        :param id: The id of this GroupOut.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and id is not None
            and not re.search(
                r"^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$|^[0-9a-fA-F]{8}[0-9a-fA-F]{4}[0-9a-fA-F]{4}[0-9a-fA-F]{4}[0-9a-fA-F]{12}$",
                id,
            )
        ):
            raise ValueError(
                r"Invalid value for `id`, must be a follow pattern or equal to `/^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$|^[0-9a-fA-F]{8}[0-9a-fA-F]{4}[0-9a-fA-F]{4}[0-9a-fA-F]{4}[0-9a-fA-F]{12}$/`"
            )

        self._id = id

    @property
    def name(self):
        """Gets the name of this GroupOut.  # noqa: E501

        A group’s human-readable name.  # noqa: E501

        :return: The name of this GroupOut.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GroupOut.

        A group’s human-readable name.  # noqa: E501

        :param name: The name of this GroupOut.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def account(self):
        """Gets the account of this GroupOut.  # noqa: E501

        A Red Hat Account number that owns the host.  # noqa: E501

        :return: The account of this GroupOut.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this GroupOut.

        A Red Hat Account number that owns the host.  # noqa: E501

        :param account: The account of this GroupOut.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def org_id(self):
        """Gets the org_id of this GroupOut.  # noqa: E501

        The Org ID of the tenant that owns the host.  # noqa: E501

        :return: The org_id of this GroupOut.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this GroupOut.

        The Org ID of the tenant that owns the host.  # noqa: E501

        :param org_id: The org_id of this GroupOut.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def ungrouped(self):
        """Gets the ungrouped of this GroupOut.  # noqa: E501

        Whether the group is the \"ungrouped hosts\" group  # noqa: E501

        :return: The ungrouped of this GroupOut.  # noqa: E501
        :rtype: bool
        """
        return self._ungrouped

    @ungrouped.setter
    def ungrouped(self, ungrouped):
        """Sets the ungrouped of this GroupOut.

        Whether the group is the \"ungrouped hosts\" group  # noqa: E501

        :param ungrouped: The ungrouped of this GroupOut.  # noqa: E501
        :type: bool
        """

        self._ungrouped = ungrouped

    @property
    def created(self):
        """Gets the created of this GroupOut.  # noqa: E501

        A timestamp when the entry was created.  # noqa: E501

        :return: The created of this GroupOut.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this GroupOut.

        A timestamp when the entry was created.  # noqa: E501

        :param created: The created of this GroupOut.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this GroupOut.  # noqa: E501

        A timestamp when the entry was last updated.  # noqa: E501

        :return: The updated of this GroupOut.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this GroupOut.

        A timestamp when the entry was last updated.  # noqa: E501

        :param updated: The updated of this GroupOut.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupOut):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupOut):
            return True

        return self.to_dict() != other.to_dict()
