"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class HostViewFilterComparison:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "eq": "str",
        "ne": "str",
        "gt": "str",
        "lt": "str",
        "gte": "str",
        "lte": "str",
        "nil": "bool",
        "not_nil": "bool",
    }

    attribute_map = {
        "eq": "eq",
        "ne": "ne",
        "gt": "gt",
        "lt": "lt",
        "gte": "gte",
        "lte": "lte",
        "nil": "nil",
        "not_nil": "not_nil",
    }

    def __init__(
        self,
        eq=None,
        ne=None,
        gt=None,
        lt=None,
        gte=None,
        lte=None,
        nil=None,
        not_nil=None,
        local_vars_configuration=None,
    ):
        """HostViewFilterComparison - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._eq = None
        self._ne = None
        self._gt = None
        self._lt = None
        self._gte = None
        self._lte = None
        self._nil = None
        self._not_nil = None
        self.discriminator = None

        if eq is not None:
            self.eq = eq
        if ne is not None:
            self.ne = ne
        if gt is not None:
            self.gt = gt
        if lt is not None:
            self.lt = lt
        if gte is not None:
            self.gte = gte
        if lte is not None:
            self.lte = lte
        if nil is not None:
            self.nil = nil
        if not_nil is not None:
            self.not_nil = not_nil

    @property
    def eq(self):
        """Gets the eq of this HostViewFilterComparison.  # noqa: E501


        :return: The eq of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._eq

    @eq.setter
    def eq(self, eq):
        """Sets the eq of this HostViewFilterComparison.


        :param eq: The eq of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._eq = eq

    @property
    def ne(self):
        """Gets the ne of this HostViewFilterComparison.  # noqa: E501


        :return: The ne of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._ne

    @ne.setter
    def ne(self, ne):
        """Sets the ne of this HostViewFilterComparison.


        :param ne: The ne of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._ne = ne

    @property
    def gt(self):
        """Gets the gt of this HostViewFilterComparison.  # noqa: E501


        :return: The gt of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._gt

    @gt.setter
    def gt(self, gt):
        """Sets the gt of this HostViewFilterComparison.


        :param gt: The gt of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._gt = gt

    @property
    def lt(self):
        """Gets the lt of this HostViewFilterComparison.  # noqa: E501


        :return: The lt of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._lt

    @lt.setter
    def lt(self, lt):
        """Sets the lt of this HostViewFilterComparison.


        :param lt: The lt of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._lt = lt

    @property
    def gte(self):
        """Gets the gte of this HostViewFilterComparison.  # noqa: E501


        :return: The gte of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._gte

    @gte.setter
    def gte(self, gte):
        """Sets the gte of this HostViewFilterComparison.


        :param gte: The gte of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._gte = gte

    @property
    def lte(self):
        """Gets the lte of this HostViewFilterComparison.  # noqa: E501


        :return: The lte of this HostViewFilterComparison.  # noqa: E501
        :rtype: str
        """
        return self._lte

    @lte.setter
    def lte(self, lte):
        """Sets the lte of this HostViewFilterComparison.


        :param lte: The lte of this HostViewFilterComparison.  # noqa: E501
        :type: str
        """

        self._lte = lte

    @property
    def nil(self):
        """Gets the nil of this HostViewFilterComparison.  # noqa: E501

        When true, matches hosts where this field is null/missing.  # noqa: E501

        :return: The nil of this HostViewFilterComparison.  # noqa: E501
        :rtype: bool
        """
        return self._nil

    @nil.setter
    def nil(self, nil):
        """Sets the nil of this HostViewFilterComparison.

        When true, matches hosts where this field is null/missing.  # noqa: E501

        :param nil: The nil of this HostViewFilterComparison.  # noqa: E501
        :type: bool
        """

        self._nil = nil

    @property
    def not_nil(self):
        """Gets the not_nil of this HostViewFilterComparison.  # noqa: E501

        When true, matches hosts where this field exists and is not null.  # noqa: E501

        :return: The not_nil of this HostViewFilterComparison.  # noqa: E501
        :rtype: bool
        """
        return self._not_nil

    @not_nil.setter
    def not_nil(self, not_nil):
        """Sets the not_nil of this HostViewFilterComparison.

        When true, matches hosts where this field exists and is not null.  # noqa: E501

        :param not_nil: The not_nil of this HostViewFilterComparison.  # noqa: E501
        :type: bool
        """

        self._not_nil = not_nil

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostViewFilterComparison):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HostViewFilterComparison):
            return True

        return self.to_dict() != other.to_dict()
