"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class PatchHostIn:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"ansible_host": "str", "display_name": "str"}

    attribute_map = {"ansible_host": "ansible_host", "display_name": "display_name"}

    def __init__(self, ansible_host=None, display_name=None, local_vars_configuration=None):
        """PatchHostIn - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ansible_host = None
        self._display_name = None
        self.discriminator = None

        if ansible_host is not None:
            self.ansible_host = ansible_host
        if display_name is not None:
            self.display_name = display_name

    @property
    def ansible_host(self):
        """Gets the ansible_host of this PatchHostIn.  # noqa: E501

        The ansible host name for remediations  # noqa: E501

        :return: The ansible_host of this PatchHostIn.  # noqa: E501
        :rtype: str
        """
        return self._ansible_host

    @ansible_host.setter
    def ansible_host(self, ansible_host):
        """Sets the ansible_host of this PatchHostIn.

        The ansible host name for remediations  # noqa: E501

        :param ansible_host: The ansible_host of this PatchHostIn.  # noqa: E501
        :type: str
        """

        self._ansible_host = ansible_host

    @property
    def display_name(self):
        """Gets the display_name of this PatchHostIn.  # noqa: E501

        A host’s human-readable display name, e.g. in a form of a domain name.  # noqa: E501

        :return: The display_name of this PatchHostIn.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this PatchHostIn.

        A host’s human-readable display name, e.g. in a form of a domain name.  # noqa: E501

        :param display_name: The display_name of this PatchHostIn.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchHostIn):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchHostIn):
            return True

        return self.to_dict() != other.to_dict()
