"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class ResourceTypesPaginationOutLinks:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"first": "str", "previous": "str", "next": "str", "last": "str"}

    attribute_map = {"first": "first", "previous": "previous", "next": "next", "last": "last"}

    def __init__(
        self, first=None, previous=None, next=None, last=None, local_vars_configuration=None
    ):
        """ResourceTypesPaginationOutLinks - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._first = None
        self._previous = None
        self._next = None
        self._last = None
        self.discriminator = None

        self.first = first
        self.previous = previous
        self.next = next
        self.last = last

    @property
    def first(self):
        """Gets the first of this ResourceTypesPaginationOutLinks.  # noqa: E501

        The URI path for the first page in the pagination  # noqa: E501

        :return: The first of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this ResourceTypesPaginationOutLinks.

        The URI path for the first page in the pagination  # noqa: E501

        :param first: The first of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and first is None:
            raise ValueError("Invalid value for `first`, must not be `None`")

        self._first = first

    @property
    def previous(self):
        """Gets the previous of this ResourceTypesPaginationOutLinks.  # noqa: E501

        The URI path for the previous page in the pagination  # noqa: E501

        :return: The previous of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :rtype: str
        """
        return self._previous

    @previous.setter
    def previous(self, previous):
        """Sets the previous of this ResourceTypesPaginationOutLinks.

        The URI path for the previous page in the pagination  # noqa: E501

        :param previous: The previous of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :type: str
        """

        self._previous = previous

    @property
    def next(self):
        """Gets the next of this ResourceTypesPaginationOutLinks.  # noqa: E501

        The URI path for the next page in the pagination  # noqa: E501

        :return: The next of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this ResourceTypesPaginationOutLinks.

        The URI path for the next page in the pagination  # noqa: E501

        :param next: The next of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def last(self):
        """Gets the last of this ResourceTypesPaginationOutLinks.  # noqa: E501

        The URI path for the last page in the pagination  # noqa: E501

        :return: The last of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this ResourceTypesPaginationOutLinks.

        The URI path for the last page in the pagination  # noqa: E501

        :param last: The last of this ResourceTypesPaginationOutLinks.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and last is None:
            raise ValueError("Invalid value for `last`, must not be `None`")

        self._last = last

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceTypesPaginationOutLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResourceTypesPaginationOutLinks):
            return True

        return self.to_dict() != other.to_dict()
