"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class StalenessIn:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "conventional_time_to_stale": "int",
        "conventional_time_to_stale_warning": "int",
        "conventional_time_to_delete": "int",
        "immutable_time_to_stale": "int",
        "immutable_time_to_stale_warning": "int",
        "immutable_time_to_delete": "int",
    }

    attribute_map = {
        "conventional_time_to_stale": "conventional_time_to_stale",
        "conventional_time_to_stale_warning": "conventional_time_to_stale_warning",
        "conventional_time_to_delete": "conventional_time_to_delete",
        "immutable_time_to_stale": "immutable_time_to_stale",
        "immutable_time_to_stale_warning": "immutable_time_to_stale_warning",
        "immutable_time_to_delete": "immutable_time_to_delete",
    }

    def __init__(
        self,
        conventional_time_to_stale=None,
        conventional_time_to_stale_warning=None,
        conventional_time_to_delete=None,
        immutable_time_to_stale=None,
        immutable_time_to_stale_warning=None,
        immutable_time_to_delete=None,
        local_vars_configuration=None,
    ):
        """StalenessIn - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._conventional_time_to_stale = None
        self._conventional_time_to_stale_warning = None
        self._conventional_time_to_delete = None
        self._immutable_time_to_stale = None
        self._immutable_time_to_stale_warning = None
        self._immutable_time_to_delete = None
        self.discriminator = None

        if conventional_time_to_stale is not None:
            self.conventional_time_to_stale = conventional_time_to_stale
        if conventional_time_to_stale_warning is not None:
            self.conventional_time_to_stale_warning = conventional_time_to_stale_warning
        if conventional_time_to_delete is not None:
            self.conventional_time_to_delete = conventional_time_to_delete
        if immutable_time_to_stale is not None:
            self.immutable_time_to_stale = immutable_time_to_stale
        if immutable_time_to_stale_warning is not None:
            self.immutable_time_to_stale_warning = immutable_time_to_stale_warning
        if immutable_time_to_delete is not None:
            self.immutable_time_to_delete = immutable_time_to_delete

    @property
    def conventional_time_to_stale(self):
        """Gets the conventional_time_to_stale of this StalenessIn.  # noqa: E501


        :return: The conventional_time_to_stale of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_stale

    @conventional_time_to_stale.setter
    def conventional_time_to_stale(self, conventional_time_to_stale):
        """Sets the conventional_time_to_stale of this StalenessIn.


        :param conventional_time_to_stale: The conventional_time_to_stale of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale is not None
            and conventional_time_to_stale < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_stale`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_stale = conventional_time_to_stale

    @property
    def conventional_time_to_stale_warning(self):
        """Gets the conventional_time_to_stale_warning of this StalenessIn.  # noqa: E501


        :return: The conventional_time_to_stale_warning of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_stale_warning

    @conventional_time_to_stale_warning.setter
    def conventional_time_to_stale_warning(self, conventional_time_to_stale_warning):
        """Sets the conventional_time_to_stale_warning of this StalenessIn.


        :param conventional_time_to_stale_warning: The conventional_time_to_stale_warning of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale_warning is not None
            and conventional_time_to_stale_warning < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_stale_warning`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_stale_warning = conventional_time_to_stale_warning

    @property
    def conventional_time_to_delete(self):
        """Gets the conventional_time_to_delete of this StalenessIn.  # noqa: E501


        :return: The conventional_time_to_delete of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_delete

    @conventional_time_to_delete.setter
    def conventional_time_to_delete(self, conventional_time_to_delete):
        """Sets the conventional_time_to_delete of this StalenessIn.


        :param conventional_time_to_delete: The conventional_time_to_delete of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_delete is not None
            and conventional_time_to_delete < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_delete`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_delete = conventional_time_to_delete

    @property
    def immutable_time_to_stale(self):
        """Gets the immutable_time_to_stale of this StalenessIn.  # noqa: E501


        :return: The immutable_time_to_stale of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_stale

    @immutable_time_to_stale.setter
    def immutable_time_to_stale(self, immutable_time_to_stale):
        """Sets the immutable_time_to_stale of this StalenessIn.


        :param immutable_time_to_stale: The immutable_time_to_stale of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale is not None
            and immutable_time_to_stale < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_stale`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_stale = immutable_time_to_stale

    @property
    def immutable_time_to_stale_warning(self):
        """Gets the immutable_time_to_stale_warning of this StalenessIn.  # noqa: E501


        :return: The immutable_time_to_stale_warning of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_stale_warning

    @immutable_time_to_stale_warning.setter
    def immutable_time_to_stale_warning(self, immutable_time_to_stale_warning):
        """Sets the immutable_time_to_stale_warning of this StalenessIn.


        :param immutable_time_to_stale_warning: The immutable_time_to_stale_warning of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale_warning is not None
            and immutable_time_to_stale_warning < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_stale_warning`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_stale_warning = immutable_time_to_stale_warning

    @property
    def immutable_time_to_delete(self):
        """Gets the immutable_time_to_delete of this StalenessIn.  # noqa: E501


        :return: The immutable_time_to_delete of this StalenessIn.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_delete

    @immutable_time_to_delete.setter
    def immutable_time_to_delete(self, immutable_time_to_delete):
        """Sets the immutable_time_to_delete of this StalenessIn.


        :param immutable_time_to_delete: The immutable_time_to_delete of this StalenessIn.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_delete is not None
            and immutable_time_to_delete < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_delete`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_delete = immutable_time_to_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StalenessIn):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StalenessIn):
            return True

        return self.to_dict() != other.to_dict()
