"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class StalenessOutput:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "conventional_time_to_stale": "int",
        "conventional_time_to_stale_warning": "int",
        "conventional_time_to_delete": "int",
        "immutable_time_to_stale": "int",
        "immutable_time_to_stale_warning": "int",
        "immutable_time_to_delete": "int",
        "id": "object",
        "org_id": "str",
        "created": "datetime",
        "updated": "datetime",
    }

    attribute_map = {
        "conventional_time_to_stale": "conventional_time_to_stale",
        "conventional_time_to_stale_warning": "conventional_time_to_stale_warning",
        "conventional_time_to_delete": "conventional_time_to_delete",
        "immutable_time_to_stale": "immutable_time_to_stale",
        "immutable_time_to_stale_warning": "immutable_time_to_stale_warning",
        "immutable_time_to_delete": "immutable_time_to_delete",
        "id": "id",
        "org_id": "org_id",
        "created": "created",
        "updated": "updated",
    }

    def __init__(
        self,
        conventional_time_to_stale=None,
        conventional_time_to_stale_warning=None,
        conventional_time_to_delete=None,
        immutable_time_to_stale=None,
        immutable_time_to_stale_warning=None,
        immutable_time_to_delete=None,
        id=None,
        org_id=None,
        created=None,
        updated=None,
        local_vars_configuration=None,
    ):
        """StalenessOutput - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._conventional_time_to_stale = None
        self._conventional_time_to_stale_warning = None
        self._conventional_time_to_delete = None
        self._immutable_time_to_stale = None
        self._immutable_time_to_stale_warning = None
        self._immutable_time_to_delete = None
        self._id = None
        self._org_id = None
        self._created = None
        self._updated = None
        self.discriminator = None

        self.conventional_time_to_stale = conventional_time_to_stale
        self.conventional_time_to_stale_warning = conventional_time_to_stale_warning
        self.conventional_time_to_delete = conventional_time_to_delete
        self.immutable_time_to_stale = immutable_time_to_stale
        self.immutable_time_to_stale_warning = immutable_time_to_stale_warning
        self.immutable_time_to_delete = immutable_time_to_delete
        self.id = id
        self.org_id = org_id
        self.created = created
        self.updated = updated

    @property
    def conventional_time_to_stale(self):
        """Gets the conventional_time_to_stale of this StalenessOutput.  # noqa: E501


        :return: The conventional_time_to_stale of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_stale

    @conventional_time_to_stale.setter
    def conventional_time_to_stale(self, conventional_time_to_stale):
        """Sets the conventional_time_to_stale of this StalenessOutput.


        :param conventional_time_to_stale: The conventional_time_to_stale of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale is None
        ):
            raise ValueError("Invalid value for `conventional_time_to_stale`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale is not None
            and conventional_time_to_stale < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_stale`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_stale = conventional_time_to_stale

    @property
    def conventional_time_to_stale_warning(self):
        """Gets the conventional_time_to_stale_warning of this StalenessOutput.  # noqa: E501


        :return: The conventional_time_to_stale_warning of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_stale_warning

    @conventional_time_to_stale_warning.setter
    def conventional_time_to_stale_warning(self, conventional_time_to_stale_warning):
        """Sets the conventional_time_to_stale_warning of this StalenessOutput.


        :param conventional_time_to_stale_warning: The conventional_time_to_stale_warning of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale_warning is None
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_stale_warning`, must not be `None`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_stale_warning is not None
            and conventional_time_to_stale_warning < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_stale_warning`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_stale_warning = conventional_time_to_stale_warning

    @property
    def conventional_time_to_delete(self):
        """Gets the conventional_time_to_delete of this StalenessOutput.  # noqa: E501


        :return: The conventional_time_to_delete of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._conventional_time_to_delete

    @conventional_time_to_delete.setter
    def conventional_time_to_delete(self, conventional_time_to_delete):
        """Sets the conventional_time_to_delete of this StalenessOutput.


        :param conventional_time_to_delete: The conventional_time_to_delete of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_delete is None
        ):
            raise ValueError("Invalid value for `conventional_time_to_delete`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and conventional_time_to_delete is not None
            and conventional_time_to_delete < 1
        ):
            raise ValueError(
                "Invalid value for `conventional_time_to_delete`, must be a value greater than or equal to `1`"
            )

        self._conventional_time_to_delete = conventional_time_to_delete

    @property
    def immutable_time_to_stale(self):
        """Gets the immutable_time_to_stale of this StalenessOutput.  # noqa: E501


        :return: The immutable_time_to_stale of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_stale

    @immutable_time_to_stale.setter
    def immutable_time_to_stale(self, immutable_time_to_stale):
        """Sets the immutable_time_to_stale of this StalenessOutput.


        :param immutable_time_to_stale: The immutable_time_to_stale of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale is None
        ):
            raise ValueError("Invalid value for `immutable_time_to_stale`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale is not None
            and immutable_time_to_stale < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_stale`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_stale = immutable_time_to_stale

    @property
    def immutable_time_to_stale_warning(self):
        """Gets the immutable_time_to_stale_warning of this StalenessOutput.  # noqa: E501


        :return: The immutable_time_to_stale_warning of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_stale_warning

    @immutable_time_to_stale_warning.setter
    def immutable_time_to_stale_warning(self, immutable_time_to_stale_warning):
        """Sets the immutable_time_to_stale_warning of this StalenessOutput.


        :param immutable_time_to_stale_warning: The immutable_time_to_stale_warning of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale_warning is None
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_stale_warning`, must not be `None`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_stale_warning is not None
            and immutable_time_to_stale_warning < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_stale_warning`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_stale_warning = immutable_time_to_stale_warning

    @property
    def immutable_time_to_delete(self):
        """Gets the immutable_time_to_delete of this StalenessOutput.  # noqa: E501


        :return: The immutable_time_to_delete of this StalenessOutput.  # noqa: E501
        :rtype: int
        """
        return self._immutable_time_to_delete

    @immutable_time_to_delete.setter
    def immutable_time_to_delete(self, immutable_time_to_delete):
        """Sets the immutable_time_to_delete of this StalenessOutput.


        :param immutable_time_to_delete: The immutable_time_to_delete of this StalenessOutput.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_delete is None
        ):
            raise ValueError("Invalid value for `immutable_time_to_delete`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and immutable_time_to_delete is not None
            and immutable_time_to_delete < 1
        ):
            raise ValueError(
                "Invalid value for `immutable_time_to_delete`, must be a value greater than or equal to `1`"
            )

        self._immutable_time_to_delete = immutable_time_to_delete

    @property
    def id(self):
        """Gets the id of this StalenessOutput.  # noqa: E501

        Account Staleness UID  # noqa: E501

        :return: The id of this StalenessOutput.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StalenessOutput.

        Account Staleness UID  # noqa: E501

        :param id: The id of this StalenessOutput.  # noqa: E501
        :type: object
        """
        if self.local_vars_configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def org_id(self):
        """Gets the org_id of this StalenessOutput.  # noqa: E501

        The Org ID of the tenant that owns the host.  # noqa: E501

        :return: The org_id of this StalenessOutput.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this StalenessOutput.

        The Org ID of the tenant that owns the host.  # noqa: E501

        :param org_id: The org_id of this StalenessOutput.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and org_id is None:
            raise ValueError("Invalid value for `org_id`, must not be `None`")

        self._org_id = org_id

    @property
    def created(self):
        """Gets the created of this StalenessOutput.  # noqa: E501

        A timestamp when the entry was created.  # noqa: E501

        :return: The created of this StalenessOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this StalenessOutput.

        A timestamp when the entry was created.  # noqa: E501

        :param created: The created of this StalenessOutput.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this StalenessOutput.  # noqa: E501

        A timestamp when the entry was last updated.  # noqa: E501

        :return: The updated of this StalenessOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this StalenessOutput.

        A timestamp when the entry was last updated.  # noqa: E501

        :param updated: The updated of this StalenessOutput.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StalenessOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StalenessOutput):
            return True

        return self.to_dict() != other.to_dict()
