"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileInterSystemsRunningInstance:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"instance_name": "str", "product": "str", "version": "str"}

    attribute_map = {"instance_name": "instance_name", "product": "product", "version": "version"}

    def __init__(
        self, instance_name=None, product=None, version=None, local_vars_configuration=None
    ):
        """SystemProfileInterSystemsRunningInstance - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._instance_name = None
        self._product = None
        self._version = None
        self.discriminator = None

        if instance_name is not None:
            self.instance_name = instance_name
        if product is not None:
            self.product = product
        if version is not None:
            self.version = version

    @property
    def instance_name(self):
        """Gets the instance_name of this SystemProfileInterSystemsRunningInstance.  # noqa: E501

        The name of the instance  # noqa: E501

        :return: The instance_name of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :rtype: str
        """
        return self._instance_name

    @instance_name.setter
    def instance_name(self, instance_name):
        """Sets the instance_name of this SystemProfileInterSystemsRunningInstance.

        The name of the instance  # noqa: E501

        :param instance_name: The instance_name of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and instance_name is not None
            and len(instance_name) > 255
        ):
            raise ValueError(
                "Invalid value for `instance_name`, length must be less than or equal to `255`"
            )

        self._instance_name = instance_name

    @property
    def product(self):
        """Gets the product of this SystemProfileInterSystemsRunningInstance.  # noqa: E501

        The product of the instance  # noqa: E501

        :return: The product of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :rtype: str
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this SystemProfileInterSystemsRunningInstance.

        The product of the instance  # noqa: E501

        :param product: The product of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and product is not None
            and len(product) > 64
        ):
            raise ValueError(
                "Invalid value for `product`, length must be less than or equal to `64`"
            )

        self._product = product

    @property
    def version(self):
        """Gets the version of this SystemProfileInterSystemsRunningInstance.  # noqa: E501

        The version of the instance  # noqa: E501

        :return: The version of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this SystemProfileInterSystemsRunningInstance.

        The version of the instance  # noqa: E501

        :param version: The version of this SystemProfileInterSystemsRunningInstance.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and version is not None
            and len(version) > 7
        ):
            raise ValueError(
                "Invalid value for `version`, length must be less than or equal to `7`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and version is not None
            and not re.search(r"^\d+(\.\d+)+$", version)
        ):
            raise ValueError(
                r"Invalid value for `version`, must be a follow pattern or equal to `/^\d+(\.\d+)+$/`"
            )

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileInterSystemsRunningInstance):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileInterSystemsRunningInstance):
            return True

        return self.to_dict() != other.to_dict()
