"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileIntersystems:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "is_intersystems": "bool",
        "running_instances": "list[SystemProfileInterSystemsRunningInstance]",
    }

    attribute_map = {
        "is_intersystems": "is_intersystems",
        "running_instances": "running_instances",
    }

    def __init__(
        self, is_intersystems=None, running_instances=None, local_vars_configuration=None
    ):
        """SystemProfileIntersystems - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._is_intersystems = None
        self._running_instances = None
        self.discriminator = None

        if is_intersystems is not None:
            self.is_intersystems = is_intersystems
        if running_instances is not None:
            self.running_instances = running_instances

    @property
    def is_intersystems(self):
        """Gets the is_intersystems of this SystemProfileIntersystems.  # noqa: E501

        Indicates if InterSystems is installed on the system  # noqa: E501

        :return: The is_intersystems of this SystemProfileIntersystems.  # noqa: E501
        :rtype: bool
        """
        return self._is_intersystems

    @is_intersystems.setter
    def is_intersystems(self, is_intersystems):
        """Sets the is_intersystems of this SystemProfileIntersystems.

        Indicates if InterSystems is installed on the system  # noqa: E501

        :param is_intersystems: The is_intersystems of this SystemProfileIntersystems.  # noqa: E501
        :type: bool
        """

        self._is_intersystems = is_intersystems

    @property
    def running_instances(self):
        """Gets the running_instances of this SystemProfileIntersystems.  # noqa: E501


        :return: The running_instances of this SystemProfileIntersystems.  # noqa: E501
        :rtype: list[SystemProfileInterSystemsRunningInstance]
        """
        return self._running_instances

    @running_instances.setter
    def running_instances(self, running_instances):
        """Sets the running_instances of this SystemProfileIntersystems.


        :param running_instances: The running_instances of this SystemProfileIntersystems.  # noqa: E501
        :type: list[SystemProfileInterSystemsRunningInstance]
        """

        self._running_instances = running_instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileIntersystems):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileIntersystems):
            return True

        return self.to_dict() != other.to_dict()
