"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileDiskDevice:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "device": "str",
        "label": "str",
        "options": "dict(str, object)",
        "mount_point": "str",
        "type": "str",
    }

    attribute_map = {
        "device": "device",
        "label": "label",
        "options": "options",
        "mount_point": "mount_point",
        "type": "type",
    }

    def __init__(
        self,
        device=None,
        label=None,
        options=None,
        mount_point=None,
        type=None,
        local_vars_configuration=None,
    ):
        """SystemProfileDiskDevice - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._device = None
        self._label = None
        self._options = None
        self._mount_point = None
        self._type = None
        self.discriminator = None

        if device is not None:
            self.device = device
        if label is not None:
            self.label = label
        if options is not None:
            self.options = options
        if mount_point is not None:
            self.mount_point = mount_point
        if type is not None:
            self.type = type

    @property
    def device(self):
        """Gets the device of this SystemProfileDiskDevice.  # noqa: E501


        :return: The device of this SystemProfileDiskDevice.  # noqa: E501
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this SystemProfileDiskDevice.


        :param device: The device of this SystemProfileDiskDevice.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and device is not None
            and len(device) > 2048
        ):
            raise ValueError(
                "Invalid value for `device`, length must be less than or equal to `2048`"
            )

        self._device = device

    @property
    def label(self):
        """Gets the label of this SystemProfileDiskDevice.  # noqa: E501

        User-defined mount label  # noqa: E501

        :return: The label of this SystemProfileDiskDevice.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SystemProfileDiskDevice.

        User-defined mount label  # noqa: E501

        :param label: The label of this SystemProfileDiskDevice.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and label is not None
            and len(label) > 1024
        ):
            raise ValueError(
                "Invalid value for `label`, length must be less than or equal to `1024`"
            )

        self._label = label

    @property
    def options(self):
        """Gets the options of this SystemProfileDiskDevice.  # noqa: E501

        An arbitrary object that does not allow empty string keys.  # noqa: E501

        :return: The options of this SystemProfileDiskDevice.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this SystemProfileDiskDevice.

        An arbitrary object that does not allow empty string keys.  # noqa: E501

        :param options: The options of this SystemProfileDiskDevice.  # noqa: E501
        :type: dict(str, object)
        """

        self._options = options

    @property
    def mount_point(self):
        """Gets the mount_point of this SystemProfileDiskDevice.  # noqa: E501

        The mount point  # noqa: E501

        :return: The mount_point of this SystemProfileDiskDevice.  # noqa: E501
        :rtype: str
        """
        return self._mount_point

    @mount_point.setter
    def mount_point(self, mount_point):
        """Sets the mount_point of this SystemProfileDiskDevice.

        The mount point  # noqa: E501

        :param mount_point: The mount_point of this SystemProfileDiskDevice.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and mount_point is not None
            and len(mount_point) > 2048
        ):
            raise ValueError(
                "Invalid value for `mount_point`, length must be less than or equal to `2048`"
            )

        self._mount_point = mount_point

    @property
    def type(self):
        """Gets the type of this SystemProfileDiskDevice.  # noqa: E501

        The mount type  # noqa: E501

        :return: The type of this SystemProfileDiskDevice.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SystemProfileDiskDevice.

        The mount type  # noqa: E501

        :param type: The type of this SystemProfileDiskDevice.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and type is not None
            and len(type) > 256
        ):
            raise ValueError(
                "Invalid value for `type`, length must be less than or equal to `256`"
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileDiskDevice):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileDiskDevice):
            return True

        return self.to_dict() != other.to_dict()
