"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileDnfModule:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"name": "str", "stream": "str", "status": "list[str]"}

    attribute_map = {"name": "name", "stream": "stream", "status": "status"}

    def __init__(self, name=None, stream=None, status=None, local_vars_configuration=None):
        """SystemProfileDnfModule - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._stream = None
        self._status = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if stream is not None:
            self.stream = stream
        if status is not None:
            self.status = status

    @property
    def name(self):
        """Gets the name of this SystemProfileDnfModule.  # noqa: E501


        :return: The name of this SystemProfileDnfModule.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemProfileDnfModule.


        :param name: The name of this SystemProfileDnfModule.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) > 128
        ):
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `128`"
            )

        self._name = name

    @property
    def stream(self):
        """Gets the stream of this SystemProfileDnfModule.  # noqa: E501


        :return: The stream of this SystemProfileDnfModule.  # noqa: E501
        :rtype: str
        """
        return self._stream

    @stream.setter
    def stream(self, stream):
        """Sets the stream of this SystemProfileDnfModule.


        :param stream: The stream of this SystemProfileDnfModule.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and stream is not None
            and len(stream) > 2048
        ):
            raise ValueError(
                "Invalid value for `stream`, length must be less than or equal to `2048`"
            )

        self._stream = stream

    @property
    def status(self):
        """Gets the status of this SystemProfileDnfModule.  # noqa: E501


        :return: The status of this SystemProfileDnfModule.  # noqa: E501
        :rtype: list[str]
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SystemProfileDnfModule.


        :param status: The status of this SystemProfileDnfModule.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["default", "enabled", "installed"]
        if self.local_vars_configuration.client_side_validation and not set(status).issubset(
            set(allowed_values)
        ):
            raise ValueError(
                "Invalid values for `status` [{}], must be a subset of [{}]".format(
                    ", ".join(map(str, set(status) - set(allowed_values))),
                    ", ".join(map(str, allowed_values)),
                )
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileDnfModule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileDnfModule):
            return True

        return self.to_dict() != other.to_dict()
