"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileImageBuilder:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"compliance_policy_id": "str", "compliance_profile_id": "str"}

    attribute_map = {
        "compliance_policy_id": "compliance_policy_id",
        "compliance_profile_id": "compliance_profile_id",
    }

    def __init__(
        self, compliance_policy_id=None, compliance_profile_id=None, local_vars_configuration=None
    ):
        """SystemProfileImageBuilder - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._compliance_policy_id = None
        self._compliance_profile_id = None
        self.discriminator = None

        if compliance_policy_id is not None:
            self.compliance_policy_id = compliance_policy_id
        if compliance_profile_id is not None:
            self.compliance_profile_id = compliance_profile_id

    @property
    def compliance_policy_id(self):
        """Gets the compliance_policy_id of this SystemProfileImageBuilder.  # noqa: E501

        The compliance policy that was used and applied during the image build  # noqa: E501

        :return: The compliance_policy_id of this SystemProfileImageBuilder.  # noqa: E501
        :rtype: str
        """
        return self._compliance_policy_id

    @compliance_policy_id.setter
    def compliance_policy_id(self, compliance_policy_id):
        """Sets the compliance_policy_id of this SystemProfileImageBuilder.

        The compliance policy that was used and applied during the image build  # noqa: E501

        :param compliance_policy_id: The compliance_policy_id of this SystemProfileImageBuilder.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and compliance_policy_id is not None
            and len(compliance_policy_id) > 36
        ):
            raise ValueError(
                "Invalid value for `compliance_policy_id`, length must be less than or equal to `36`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and compliance_policy_id is not None
            and not re.search(
                r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
                compliance_policy_id,
            )
        ):
            raise ValueError(
                r"Invalid value for `compliance_policy_id`, must be a follow pattern or equal to `/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/`"
            )

        self._compliance_policy_id = compliance_policy_id

    @property
    def compliance_profile_id(self):
        """Gets the compliance_profile_id of this SystemProfileImageBuilder.  # noqa: E501

        The profile that was applied during the image build on which the compliance policy was based   # noqa: E501

        :return: The compliance_profile_id of this SystemProfileImageBuilder.  # noqa: E501
        :rtype: str
        """
        return self._compliance_profile_id

    @compliance_profile_id.setter
    def compliance_profile_id(self, compliance_profile_id):
        """Sets the compliance_profile_id of this SystemProfileImageBuilder.

        The profile that was applied during the image build on which the compliance policy was based   # noqa: E501

        :param compliance_profile_id: The compliance_profile_id of this SystemProfileImageBuilder.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and compliance_profile_id is not None
            and len(compliance_profile_id) > 255
        ):
            raise ValueError(
                "Invalid value for `compliance_profile_id`, length must be less than or equal to `255`"
            )

        self._compliance_profile_id = compliance_profile_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileImageBuilder):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileImageBuilder):
            return True

        return self.to_dict() != other.to_dict()
