"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileOperatingSystemOutValue:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"name": "str", "major": "int", "minor": "int"}

    attribute_map = {"name": "name", "major": "major", "minor": "minor"}

    def __init__(self, name=None, major=None, minor=None, local_vars_configuration=None):
        """SystemProfileOperatingSystemOutValue - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._major = None
        self._minor = None
        self.discriminator = None

        if name is not None:
            self.name = name
        self.major = major
        self.minor = minor

    @property
    def name(self):
        """Gets the name of this SystemProfileOperatingSystemOutValue.  # noqa: E501


        :return: The name of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemProfileOperatingSystemOutValue.


        :param name: The name of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def major(self):
        """Gets the major of this SystemProfileOperatingSystemOutValue.  # noqa: E501


        :return: The major of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :rtype: int
        """
        return self._major

    @major.setter
    def major(self, major):
        """Sets the major of this SystemProfileOperatingSystemOutValue.


        :param major: The major of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :type: int
        """

        self._major = major

    @property
    def minor(self):
        """Gets the minor of this SystemProfileOperatingSystemOutValue.  # noqa: E501


        :return: The minor of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :rtype: int
        """
        return self._minor

    @minor.setter
    def minor(self, minor):
        """Sets the minor of this SystemProfileOperatingSystemOutValue.


        :param minor: The minor of this SystemProfileOperatingSystemOutValue.  # noqa: E501
        :type: int
        """

        self._minor = minor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileOperatingSystemOutValue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileOperatingSystemOutValue):
            return True

        return self.to_dict() != other.to_dict()
