"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileNetworkInterface:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "ipv4_addresses": "list[str]",
        "ipv6_addresses": "list[str]",
        "mtu": "int",
        "mac_address": "str",
        "name": "str",
        "state": "str",
        "type": "str",
    }

    attribute_map = {
        "ipv4_addresses": "ipv4_addresses",
        "ipv6_addresses": "ipv6_addresses",
        "mtu": "mtu",
        "mac_address": "mac_address",
        "name": "name",
        "state": "state",
        "type": "type",
    }

    def __init__(
        self,
        ipv4_addresses=None,
        ipv6_addresses=None,
        mtu=None,
        mac_address=None,
        name=None,
        state=None,
        type=None,
        local_vars_configuration=None,
    ):
        """SystemProfileNetworkInterface - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ipv4_addresses = None
        self._ipv6_addresses = None
        self._mtu = None
        self._mac_address = None
        self._name = None
        self._state = None
        self._type = None
        self.discriminator = None

        if ipv4_addresses is not None:
            self.ipv4_addresses = ipv4_addresses
        if ipv6_addresses is not None:
            self.ipv6_addresses = ipv6_addresses
        if mtu is not None:
            self.mtu = mtu
        if mac_address is not None:
            self.mac_address = mac_address
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if type is not None:
            self.type = type

    @property
    def ipv4_addresses(self):
        """Gets the ipv4_addresses of this SystemProfileNetworkInterface.  # noqa: E501


        :return: The ipv4_addresses of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: list[str]
        """
        return self._ipv4_addresses

    @ipv4_addresses.setter
    def ipv4_addresses(self, ipv4_addresses):
        """Sets the ipv4_addresses of this SystemProfileNetworkInterface.


        :param ipv4_addresses: The ipv4_addresses of this SystemProfileNetworkInterface.  # noqa: E501
        :type: list[str]
        """

        self._ipv4_addresses = ipv4_addresses

    @property
    def ipv6_addresses(self):
        """Gets the ipv6_addresses of this SystemProfileNetworkInterface.  # noqa: E501


        :return: The ipv6_addresses of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: list[str]
        """
        return self._ipv6_addresses

    @ipv6_addresses.setter
    def ipv6_addresses(self, ipv6_addresses):
        """Sets the ipv6_addresses of this SystemProfileNetworkInterface.


        :param ipv6_addresses: The ipv6_addresses of this SystemProfileNetworkInterface.  # noqa: E501
        :type: list[str]
        """

        self._ipv6_addresses = ipv6_addresses

    @property
    def mtu(self):
        """Gets the mtu of this SystemProfileNetworkInterface.  # noqa: E501

        MTU (Maximum transmission unit)  # noqa: E501

        :return: The mtu of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: int
        """
        return self._mtu

    @mtu.setter
    def mtu(self, mtu):
        """Sets the mtu of this SystemProfileNetworkInterface.

        MTU (Maximum transmission unit)  # noqa: E501

        :param mtu: The mtu of this SystemProfileNetworkInterface.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation
            and mtu is not None
            and mtu > 2147483647
        ):
            raise ValueError(
                "Invalid value for `mtu`, must be a value less than or equal to `2147483647`"
            )
        if self.local_vars_configuration.client_side_validation and mtu is not None and mtu < 0:
            raise ValueError(
                "Invalid value for `mtu`, must be a value greater than or equal to `0`"
            )

        self._mtu = mtu

    @property
    def mac_address(self):
        """Gets the mac_address of this SystemProfileNetworkInterface.  # noqa: E501

        MAC address (with or without colons)  # noqa: E501

        :return: The mac_address of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address):
        """Sets the mac_address of this SystemProfileNetworkInterface.

        MAC address (with or without colons)  # noqa: E501

        :param mac_address: The mac_address of this SystemProfileNetworkInterface.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and mac_address is not None
            and len(mac_address) > 59
        ):
            raise ValueError(
                "Invalid value for `mac_address`, length must be less than or equal to `59`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and mac_address is not None
            and not re.search(
                r"^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$|^([A-Fa-f0-9]{4}[.]){2}[A-Fa-f0-9]{4}$|^[A-Fa-f0-9]{12}$|^([A-Fa-f0-9]{2}[:-]){19}[A-Fa-f0-9]{2}$|^[A-Fa-f0-9]{40}$",
                mac_address,
            )
        ):
            raise ValueError(
                r"Invalid value for `mac_address`, must be a follow pattern or equal to `/^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$|^([A-Fa-f0-9]{4}[.]){2}[A-Fa-f0-9]{4}$|^[A-Fa-f0-9]{12}$|^([A-Fa-f0-9]{2}[:-]){19}[A-Fa-f0-9]{2}$|^[A-Fa-f0-9]{40}$/`"
            )

        self._mac_address = mac_address

    @property
    def name(self):
        """Gets the name of this SystemProfileNetworkInterface.  # noqa: E501

        Name of interface  # noqa: E501

        :return: The name of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemProfileNetworkInterface.

        Name of interface  # noqa: E501

        :param name: The name of this SystemProfileNetworkInterface.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) > 50
        ):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) < 1
        ):
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )

        self._name = name

    @property
    def state(self):
        """Gets the state of this SystemProfileNetworkInterface.  # noqa: E501

        Interface state (UP, DOWN, UNKNOWN)  # noqa: E501

        :return: The state of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this SystemProfileNetworkInterface.

        Interface state (UP, DOWN, UNKNOWN)  # noqa: E501

        :param state: The state of this SystemProfileNetworkInterface.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and state is not None
            and len(state) > 25
        ):
            raise ValueError(
                "Invalid value for `state`, length must be less than or equal to `25`"
            )

        self._state = state

    @property
    def type(self):
        """Gets the type of this SystemProfileNetworkInterface.  # noqa: E501

        Interface type (ether, loopback)  # noqa: E501

        :return: The type of this SystemProfileNetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SystemProfileNetworkInterface.

        Interface type (ether, loopback)  # noqa: E501

        :param type: The type of this SystemProfileNetworkInterface.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and type is not None
            and len(type) > 18
        ):
            raise ValueError("Invalid value for `type`, length must be less than or equal to `18`")

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileNetworkInterface):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileNetworkInterface):
            return True

        return self.to_dict() != other.to_dict()
