"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileAnsible:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "controller_version": "str",
        "hub_version": "str",
        "catalog_worker_version": "str",
        "sso_version": "str",
    }

    attribute_map = {
        "controller_version": "controller_version",
        "hub_version": "hub_version",
        "catalog_worker_version": "catalog_worker_version",
        "sso_version": "sso_version",
    }

    def __init__(
        self,
        controller_version=None,
        hub_version=None,
        catalog_worker_version=None,
        sso_version=None,
        local_vars_configuration=None,
    ):
        """SystemProfileAnsible - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._controller_version = None
        self._hub_version = None
        self._catalog_worker_version = None
        self._sso_version = None
        self.discriminator = None

        if controller_version is not None:
            self.controller_version = controller_version
        if hub_version is not None:
            self.hub_version = hub_version
        if catalog_worker_version is not None:
            self.catalog_worker_version = catalog_worker_version
        if sso_version is not None:
            self.sso_version = sso_version

    @property
    def controller_version(self):
        """Gets the controller_version of this SystemProfileAnsible.  # noqa: E501

        The ansible-tower or automation-controller version on the host  # noqa: E501

        :return: The controller_version of this SystemProfileAnsible.  # noqa: E501
        :rtype: str
        """
        return self._controller_version

    @controller_version.setter
    def controller_version(self, controller_version):
        """Sets the controller_version of this SystemProfileAnsible.

        The ansible-tower or automation-controller version on the host  # noqa: E501

        :param controller_version: The controller_version of this SystemProfileAnsible.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and controller_version is not None
            and len(controller_version) > 30
        ):
            raise ValueError(
                "Invalid value for `controller_version`, length must be less than or equal to `30`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and controller_version is not None
            and not re.search(r"^\d+(\.\d+)+$", controller_version)
        ):
            raise ValueError(
                r"Invalid value for `controller_version`, must be a follow pattern or equal to `/^\d+(\.\d+)+$/`"
            )

        self._controller_version = controller_version

    @property
    def hub_version(self):
        """Gets the hub_version of this SystemProfileAnsible.  # noqa: E501

        The automation-hub version on the host  # noqa: E501

        :return: The hub_version of this SystemProfileAnsible.  # noqa: E501
        :rtype: str
        """
        return self._hub_version

    @hub_version.setter
    def hub_version(self, hub_version):
        """Sets the hub_version of this SystemProfileAnsible.

        The automation-hub version on the host  # noqa: E501

        :param hub_version: The hub_version of this SystemProfileAnsible.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and hub_version is not None
            and len(hub_version) > 30
        ):
            raise ValueError(
                "Invalid value for `hub_version`, length must be less than or equal to `30`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and hub_version is not None
            and not re.search(r"^\d+(\.\d+)+$", hub_version)
        ):
            raise ValueError(
                r"Invalid value for `hub_version`, must be a follow pattern or equal to `/^\d+(\.\d+)+$/`"
            )

        self._hub_version = hub_version

    @property
    def catalog_worker_version(self):
        """Gets the catalog_worker_version of this SystemProfileAnsible.  # noqa: E501

        The catalog-worker version on the host  # noqa: E501

        :return: The catalog_worker_version of this SystemProfileAnsible.  # noqa: E501
        :rtype: str
        """
        return self._catalog_worker_version

    @catalog_worker_version.setter
    def catalog_worker_version(self, catalog_worker_version):
        """Sets the catalog_worker_version of this SystemProfileAnsible.

        The catalog-worker version on the host  # noqa: E501

        :param catalog_worker_version: The catalog_worker_version of this SystemProfileAnsible.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and catalog_worker_version is not None
            and len(catalog_worker_version) > 30
        ):
            raise ValueError(
                "Invalid value for `catalog_worker_version`, length must be less than or equal to `30`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and catalog_worker_version is not None
            and not re.search(r"^\d+(\.\d+)+$", catalog_worker_version)
        ):
            raise ValueError(
                r"Invalid value for `catalog_worker_version`, must be a follow pattern or equal to `/^\d+(\.\d+)+$/`"
            )

        self._catalog_worker_version = catalog_worker_version

    @property
    def sso_version(self):
        """Gets the sso_version of this SystemProfileAnsible.  # noqa: E501

        The SSO version on the host  # noqa: E501

        :return: The sso_version of this SystemProfileAnsible.  # noqa: E501
        :rtype: str
        """
        return self._sso_version

    @sso_version.setter
    def sso_version(self, sso_version):
        """Sets the sso_version of this SystemProfileAnsible.

        The SSO version on the host  # noqa: E501

        :param sso_version: The sso_version of this SystemProfileAnsible.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and sso_version is not None
            and len(sso_version) > 30
        ):
            raise ValueError(
                "Invalid value for `sso_version`, length must be less than or equal to `30`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and sso_version is not None
            and not re.search(r"^\d+(\.\d+)+$", sso_version)
        ):
            raise ValueError(
                r"Invalid value for `sso_version`, must be a follow pattern or equal to `/^\d+(\.\d+)+$/`"
            )

        self._sso_version = sso_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileAnsible):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileAnsible):
            return True

        return self.to_dict() != other.to_dict()
