"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileOperatingSystemOut:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "total": "int",
        "count": "int",
        "results": "list[SystemProfileOperatingSystemOutResults]",
    }

    attribute_map = {"total": "total", "count": "count", "results": "results"}

    def __init__(self, total=None, count=None, results=None, local_vars_configuration=None):
        """SystemProfileOperatingSystemOut - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._total = None
        self._count = None
        self._results = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if count is not None:
            self.count = count
        if results is not None:
            self.results = results

    @property
    def total(self):
        """Gets the total of this SystemProfileOperatingSystemOut.  # noqa: E501

        Total number of items  # noqa: E501

        :return: The total of this SystemProfileOperatingSystemOut.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this SystemProfileOperatingSystemOut.

        Total number of items  # noqa: E501

        :param total: The total of this SystemProfileOperatingSystemOut.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def count(self):
        """Gets the count of this SystemProfileOperatingSystemOut.  # noqa: E501

        The number of items on the current page  # noqa: E501

        :return: The count of this SystemProfileOperatingSystemOut.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this SystemProfileOperatingSystemOut.

        The number of items on the current page  # noqa: E501

        :param count: The count of this SystemProfileOperatingSystemOut.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def results(self):
        """Gets the results of this SystemProfileOperatingSystemOut.  # noqa: E501

        The list of operating_system values on the account  # noqa: E501

        :return: The results of this SystemProfileOperatingSystemOut.  # noqa: E501
        :rtype: list[SystemProfileOperatingSystemOutResults]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this SystemProfileOperatingSystemOut.

        The list of operating_system values on the account  # noqa: E501

        :param results: The results of this SystemProfileOperatingSystemOut.  # noqa: E501
        :type: list[SystemProfileOperatingSystemOutResults]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileOperatingSystemOut):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileOperatingSystemOut):
            return True

        return self.to_dict() != other.to_dict()
