"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileYumRepo:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "id": "str",
        "name": "str",
        "gpgcheck": "bool",
        "enabled": "bool",
        "base_url": "str",
        "mirrorlist": "str",
    }

    attribute_map = {
        "id": "id",
        "name": "name",
        "gpgcheck": "gpgcheck",
        "enabled": "enabled",
        "base_url": "base_url",
        "mirrorlist": "mirrorlist",
    }

    def __init__(
        self,
        id=None,
        name=None,
        gpgcheck=None,
        enabled=None,
        base_url=None,
        mirrorlist=None,
        local_vars_configuration=None,
    ):
        """SystemProfileYumRepo - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._gpgcheck = None
        self._enabled = None
        self._base_url = None
        self._mirrorlist = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if gpgcheck is not None:
            self.gpgcheck = gpgcheck
        if enabled is not None:
            self.enabled = enabled
        if base_url is not None:
            self.base_url = base_url
        if mirrorlist is not None:
            self.mirrorlist = mirrorlist

    @property
    def id(self):
        """Gets the id of this SystemProfileYumRepo.  # noqa: E501


        :return: The id of this SystemProfileYumRepo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SystemProfileYumRepo.


        :param id: The id of this SystemProfileYumRepo.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and id is not None
            and len(id) > 256
        ):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `256`")

        self._id = id

    @property
    def name(self):
        """Gets the name of this SystemProfileYumRepo.  # noqa: E501


        :return: The name of this SystemProfileYumRepo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemProfileYumRepo.


        :param name: The name of this SystemProfileYumRepo.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) > 1024
        ):
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `1024`"
            )

        self._name = name

    @property
    def gpgcheck(self):
        """Gets the gpgcheck of this SystemProfileYumRepo.  # noqa: E501


        :return: The gpgcheck of this SystemProfileYumRepo.  # noqa: E501
        :rtype: bool
        """
        return self._gpgcheck

    @gpgcheck.setter
    def gpgcheck(self, gpgcheck):
        """Sets the gpgcheck of this SystemProfileYumRepo.


        :param gpgcheck: The gpgcheck of this SystemProfileYumRepo.  # noqa: E501
        :type: bool
        """

        self._gpgcheck = gpgcheck

    @property
    def enabled(self):
        """Gets the enabled of this SystemProfileYumRepo.  # noqa: E501


        :return: The enabled of this SystemProfileYumRepo.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this SystemProfileYumRepo.


        :param enabled: The enabled of this SystemProfileYumRepo.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def base_url(self):
        """Gets the base_url of this SystemProfileYumRepo.  # noqa: E501


        :return: The base_url of this SystemProfileYumRepo.  # noqa: E501
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url):
        """Sets the base_url of this SystemProfileYumRepo.


        :param base_url: The base_url of this SystemProfileYumRepo.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and base_url is not None
            and len(base_url) > 2048
        ):
            raise ValueError(
                "Invalid value for `base_url`, length must be less than or equal to `2048`"
            )

        self._base_url = base_url

    @property
    def mirrorlist(self):
        """Gets the mirrorlist of this SystemProfileYumRepo.  # noqa: E501

        URL of a mirrorlist for the repository  # noqa: E501

        :return: The mirrorlist of this SystemProfileYumRepo.  # noqa: E501
        :rtype: str
        """
        return self._mirrorlist

    @mirrorlist.setter
    def mirrorlist(self, mirrorlist):
        """Sets the mirrorlist of this SystemProfileYumRepo.

        URL of a mirrorlist for the repository  # noqa: E501

        :param mirrorlist: The mirrorlist of this SystemProfileYumRepo.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and mirrorlist is not None
            and len(mirrorlist) > 2048
        ):
            raise ValueError(
                "Invalid value for `mirrorlist`, length must be less than or equal to `2048`"
            )

        self._mirrorlist = mirrorlist

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileYumRepo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileYumRepo):
            return True

        return self.to_dict() != other.to_dict()
