"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class SystemProfileSystemd:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "state": "str",
        "jobs_queued": "int",
        "failed": "int",
        "failed_services": "list[str]",
    }

    attribute_map = {
        "state": "state",
        "jobs_queued": "jobs_queued",
        "failed": "failed",
        "failed_services": "failed_services",
    }

    def __init__(
        self,
        state=None,
        jobs_queued=None,
        failed=None,
        failed_services=None,
        local_vars_configuration=None,
    ):
        """SystemProfileSystemd - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._state = None
        self._jobs_queued = None
        self._failed = None
        self._failed_services = None
        self.discriminator = None

        self.state = state
        self.jobs_queued = jobs_queued
        self.failed = failed
        if failed_services is not None:
            self.failed_services = failed_services

    @property
    def state(self):
        """Gets the state of this SystemProfileSystemd.  # noqa: E501

        The state of the systemd subsystem  # noqa: E501

        :return: The state of this SystemProfileSystemd.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this SystemProfileSystemd.

        The state of the systemd subsystem  # noqa: E501

        :param state: The state of this SystemProfileSystemd.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")
        allowed_values = [
            "initializing",
            "starting",
            "running",
            "degraded",
            "maintenance",
            "stopping",
        ]
        if self.local_vars_configuration.client_side_validation and state not in allowed_values:
            raise ValueError(
                f"Invalid value for `state` ({state}), must be one of {allowed_values}"
            )

        self._state = state

    @property
    def jobs_queued(self):
        """Gets the jobs_queued of this SystemProfileSystemd.  # noqa: E501

        The number of jobs jobs_queued  # noqa: E501

        :return: The jobs_queued of this SystemProfileSystemd.  # noqa: E501
        :rtype: int
        """
        return self._jobs_queued

    @jobs_queued.setter
    def jobs_queued(self, jobs_queued):
        """Sets the jobs_queued of this SystemProfileSystemd.

        The number of jobs jobs_queued  # noqa: E501

        :param jobs_queued: The jobs_queued of this SystemProfileSystemd.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and jobs_queued is None:
            raise ValueError("Invalid value for `jobs_queued`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and jobs_queued is not None
            and jobs_queued < 0
        ):
            raise ValueError(
                "Invalid value for `jobs_queued`, must be a value greater than or equal to `0`"
            )

        self._jobs_queued = jobs_queued

    @property
    def failed(self):
        """Gets the failed of this SystemProfileSystemd.  # noqa: E501

        The number of jobs failed  # noqa: E501

        :return: The failed of this SystemProfileSystemd.  # noqa: E501
        :rtype: int
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this SystemProfileSystemd.

        The number of jobs failed  # noqa: E501

        :param failed: The failed of this SystemProfileSystemd.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and failed is None:
            raise ValueError("Invalid value for `failed`, must not be `None`")
        if (
            self.local_vars_configuration.client_side_validation
            and failed is not None
            and failed < 0
        ):
            raise ValueError(
                "Invalid value for `failed`, must be a value greater than or equal to `0`"
            )

        self._failed = failed

    @property
    def failed_services(self):
        """Gets the failed_services of this SystemProfileSystemd.  # noqa: E501

        List of all failed jobs.  # noqa: E501

        :return: The failed_services of this SystemProfileSystemd.  # noqa: E501
        :rtype: list[str]
        """
        return self._failed_services

    @failed_services.setter
    def failed_services(self, failed_services):
        """Sets the failed_services of this SystemProfileSystemd.

        List of all failed jobs.  # noqa: E501

        :param failed_services: The failed_services of this SystemProfileSystemd.  # noqa: E501
        :type: list[str]
        """

        self._failed_services = failed_services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfileSystemd):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SystemProfileSystemd):
            return True

        return self.to_dict() != other.to_dict()
