"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class ViewColumnConfig:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"key": "str", "visible": "bool"}

    attribute_map = {"key": "key", "visible": "visible"}

    def __init__(self, key=None, visible=True, local_vars_configuration=None):
        """ViewColumnConfig - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._key = None
        self._visible = None
        self.discriminator = None

        self.key = key
        if visible is not None:
            self.visible = visible

    @property
    def key(self):
        """Gets the key of this ViewColumnConfig.  # noqa: E501

        The column key identifier, e.g. \"insights_id\", \"compliance.last_scan\", \"advisor.recommendations\".  # noqa: E501

        :return: The key of this ViewColumnConfig.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ViewColumnConfig.

        The column key identifier, e.g. \"insights_id\", \"compliance.last_scan\", \"advisor.recommendations\".  # noqa: E501

        :param key: The key of this ViewColumnConfig.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")

        self._key = key

    @property
    def visible(self):
        """Gets the visible of this ViewColumnConfig.  # noqa: E501

        Whether the column is visible in the view.  # noqa: E501

        :return: The visible of this ViewColumnConfig.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this ViewColumnConfig.

        Whether the column is visible in the view.  # noqa: E501

        :param visible: The visible of this ViewColumnConfig.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViewColumnConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ViewColumnConfig):
            return True

        return self.to_dict() != other.to_dict()
