"""
Insights Host Inventory REST Interface

REST interface for the Insights Platform Host Inventory application.  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

from iqe_host_inventory_api.configuration import Configuration


class ViewPatch:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "name": "str",
        "description": "str",
        "configuration": "ViewConfiguration",
        "org_wide": "bool",
    }

    attribute_map = {
        "name": "name",
        "description": "description",
        "configuration": "configuration",
        "org_wide": "org_wide",
    }

    def __init__(
        self,
        name=None,
        description=None,
        configuration=None,
        org_wide=None,
        local_vars_configuration=None,
    ):
        """ViewPatch - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._description = None
        self._configuration = None
        self._org_wide = None
        self.discriminator = None

        if name is not None:
            self.name = name
        self.description = description
        if configuration is not None:
            self.configuration = configuration
        if org_wide is not None:
            self.org_wide = org_wide

    @property
    def name(self):
        """Gets the name of this ViewPatch.  # noqa: E501

        The display name for the view.  # noqa: E501

        :return: The name of this ViewPatch.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ViewPatch.

        The display name for the view.  # noqa: E501

        :param name: The name of this ViewPatch.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) > 255
        ):
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `255`"
            )
        if (
            self.local_vars_configuration.client_side_validation
            and name is not None
            and len(name) < 1
        ):
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )

        self._name = name

    @property
    def description(self):
        """Gets the description of this ViewPatch.  # noqa: E501

        An optional description of the view.  # noqa: E501

        :return: The description of this ViewPatch.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ViewPatch.

        An optional description of the view.  # noqa: E501

        :param description: The description of this ViewPatch.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and description is not None
            and len(description) > 2048
        ):
            raise ValueError(
                "Invalid value for `description`, length must be less than or equal to `2048`"
            )

        self._description = description

    @property
    def configuration(self):
        """Gets the configuration of this ViewPatch.  # noqa: E501


        :return: The configuration of this ViewPatch.  # noqa: E501
        :rtype: ViewConfiguration
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this ViewPatch.


        :param configuration: The configuration of this ViewPatch.  # noqa: E501
        :type: ViewConfiguration
        """

        self._configuration = configuration

    @property
    def org_wide(self):
        """Gets the org_wide of this ViewPatch.  # noqa: E501

        If true, the view is visible to all users in the organization. If false, only the creator can see it.  # noqa: E501

        :return: The org_wide of this ViewPatch.  # noqa: E501
        :rtype: bool
        """
        return self._org_wide

    @org_wide.setter
    def org_wide(self, org_wide):
        """Sets the org_wide of this ViewPatch.

        If true, the view is visible to all users in the organization. If false, only the creator can see it.  # noqa: E501

        :param org_wide: The org_wide of this ViewPatch.  # noqa: E501
        :type: bool
        """

        self._org_wide = org_wide

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = [x.to_dict() if hasattr(x, "to_dict") else x for x in value]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViewPatch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ViewPatch):
            return True

        return self.to_dict() != other.to_dict()
