name: Dependabot Auto-merge
on:
  pull_request_target:
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Metadata for PR
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.AUTOMERGE_APP_ID }}
          private-key: ${{ secrets.AUTOMERGE_APP_PRIVATE_KEY }}
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') && (
                steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
                steps.metadata.outputs.update-type == 'version-update:semver-patch'
              )}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
