name: Hermetic Updates

on:
  schedule:
    - cron: '0 3 * * 0' # Runs weekly at 3:00 AM UTC on Sunday
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  COMMIT_TITLE: "build: Update hermetic lockfiles"
  PR_TITLE: "build: Update hermetic lockfiles"
  PR_BODY: "Automated hermetic lockfile update"

jobs:
  hermetic-updates:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/python-312
      options: "--user root:root -v /usr/bin:/mnt/usrbin"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Subscribe to Red Hat
        run: |
          subscription-manager register \
            --org='${{ secrets.BUILD_RH_ORG_ID }}' \
            --activationkey='${{ secrets.BUILD_RH_ORG_ACTIVATION_KEY }}'

      - name: Install prerequisites
        run: |
          sed -i 's/include-system-site-packages = false/include-system-site-packages = true/' $APP_ROOT/pyvenv.cfg
          dnf install -y skopeo
          UV_VERSION=$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['tool']['uv']['required-version'])") && \
            python3 -m pip install "uv==${UV_VERSION}"
          python3 -m pip install https://github.com/konflux-ci/rpm-lockfile-prototype/archive/refs/heads/main.zip

      - name: Run the hermetic lockfile updates
        run: |
          source $APP_ROOT/bin/activate
          make generate-hermetic-lockfiles BASE_IMAGE=local

      - name: Check for changes
        id: check-changes
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git add .
          if git diff --cached --quiet; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate token
        id: app-token
        if: steps.check-changes.outputs.changes_made == 'true'
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.AUTOMERGE_APP_ID }}
          private-key: ${{ secrets.AUTOMERGE_APP_PRIVATE_KEY }}

      - name: Create pull request
        if: steps.check-changes.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          sign-commits: true
          commit-message: ${{ env.COMMIT_TITLE }}
          title: ${{ env.PR_TITLE }}
          body: ${{ env.PR_BODY }}
          branch: hermetic_updates
          committer: 'insights-inventory-bot[bot] <insights-inventory-bot[bot]@users.noreply.github.com>'

      - name: Unsubscribe (cleanup)
        if: always()
        run: |
          subscription-manager unregister || true
